### ISSUE TITLE
Issues in some functions

### ISSUE THREAD

**Issue by yungwai** [epiforecasts/EpiNow2#103]
Hi Sam and Co. thanks for the hardwork in the development of this improved Rt estimation package. 

I followed this example to get started: https://epiforecasts.io/EpiNow2/index.html. 

I first installed the stable verison and then the stable development version. It seems like some of the functions or parameters in the function is not working on my computer. For instance, 
- `get_generation_time( )` resulted in error message: _could not find function "get generation time"_, same as `get_incubation_period( )` . 
- I could replace these two with (perhaps older) `covid_generation_times` and `covid_inubcation_period`, but while running the epinow example

```
out <- epinow(reported_cases = reported_cases, generation_time = covid_generation_times,
              delays = list(covid_incubation_period, reporting_delay),
              stan_args = list(warmup = 200, cores = ifelse(interactive(), 4, 1)))

```
result in error message "unused argument (stan_args = list(warmup = 200, cores = ifelse(interactive(), 4, 1)))"

I have Rtools installed and working ok with EpiEstim. I am using Windows OS and the R version is 3.6.1. Is there a newer example/ function I should use instead? Many thanks in advance.

**Comment by seabbs** [comment]
Hi @yungwai, 

Thanks for opening this and sorry you had problems. It seems like there may have been an issue with the package version you have installed (or formal versioning has been loose up to now but that is now changing). 

Could you try reinstalling using: 

```r
remotes::install_github("epiforecasts/EpiNow2")
```

We should be pushing a new version to CRAN etc in the next few days which should resolve some of the documentation/release mismatch (and moving to a more robust system there as well). 

Thanks, 

Sam

P.S If above doesn't resolve your issues please do ping this thread (ideally including the package version you have installed and the exact error messages you see). Also we are planning a final breaking interface change in the next day or so (#102) that may require some updates on your end.

**Comment by yungwai** [comment]
Hi @seabbs,

Thanks for your suggestion. I tried to install follow your suggestion. 

```
> remotes::install_github("epiforecasts/EpiNow2")
Downloading GitHub repo epiforecasts/EpiNow2@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                  
 2: CRAN packages only                   
 3: None                                 
 4: rlang       (0.4.5  -> 0.4.8 ) [CRAN]
 5: isoband     (0.2.0  -> 0.2.2 ) [CRAN]
 6: tibble      (2.1.3  -> 3.0.3 ) [CRAN]
 7: withr       (2.1.2  -> 2.3.0 ) [CRAN]
 8: ellipsis    (0.3.0  -> 0.3.1 ) [CRAN]
 9: fansi       (0.4.0  -> 0.4.1 ) [CRAN]
10: pillar      (1.4.3  -> 1.4.6 ) [CRAN]
11: vctrs       (0.2.4  -> 0.3.4 ) [CRAN]
12: pkgload     (1.0.2  -> 1.1.0 ) [CRAN]
13: pkgbuild    (1.0.6  -> 1.1.0 ) [CRAN]
14: callr       (3.4.3  -> 3.5.0 ) [CRAN]
15: backports   (1.1.4  -> 1.1.10) [CRAN]
16: processx    (3.4.2  -> 3.4.4 ) [CRAN]
17: ps          (1.3.2  -> 1.4.0 ) [CRAN]
18: R.methodsS3 (1.8.0  -> 1.8.1 ) [CRAN]
19: matrixStats (0.56.0 -> 0.57.0) [CRAN]
20: jsonlite    (1.6    -> 1.7.1 ) [CRAN]
21: R.oo        (1.23.0 -> 1.24.0) [CRAN]
22: inline      (0.3.15 -> 0.3.16) [CRAN]
23: loo         (2.2.0  -> 2.3.1 ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
```
I first tried "3" i.e. do not update packages. But there is an error of failed to install due to "non-zero exit status". Full message as follow for reference.

```
√  checking for file 'C:\Users\yungwai\AppData\Local\Temp\RtmpuMxROD\remotescec13144dad\epiforecasts-EpiNow2-746be29/DESCRIPTION' ... 
-  preparing 'EpiNow2': (1.3s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (599ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'EpiNow2_1.2.0.tar.gz'
   
Installing package into ‘C:/Users/yungwai/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
ERROR: failed to lock directory 'C:/Users/yungwai/Documents/R/win-library/3.6' for modifying
Try removing 'C:/Users/yungwai/Documents/R/win-library/3.6/00LOCK-EpiNow2'
Error: Failed to install 'EpiNow2' from GitHub:
  (converted from warning) installation of package ‘C:/Users/yungwai/AppData/Local/Temp/RtmpuMxROD/filecec4d0d34f5/EpiNow2_1.2.0.tar.gz’ had non-zero exit status
```

Then I tried option 1 or 2 (i.e. update all or packages in CRAN only). But it seems like some of the dependent package cannot be removed during the update, even if I tried to remove manually. Here is an example:

```
package ‘isoband’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘withr’ successfully unpacked and MD5 sums checked
package ‘ellipsis’ successfully unpacked and MD5 sums checked
package ‘fansi’ successfully unpacked and MD5 sums checked
Error: Failed to install 'EpiNow2' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘fansi’
> remove.packages("fansi")
Removing package from ‘C:/Users/yungwai/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Error in remove.packages : there is no package called ‘fansi’
```
I found some discussions on similar issues. But doesn't seem to resolve my installation issue. 
https://community.rstudio.com/t/unable-to-update-rlang/45955
https://github.com/renanxcortes/springerQuarantineBooksR/issues/41

Not sure if I have installed it properly?

**Comment by medewitt** [comment]
@yungwai  I was just updating myself. Make sure you close any and all R sessions.

Then in Windows explorer navigate to 

```
C:/Users/yungwai/Documents/R/win-library/3.6/00LOCK-EpiNow2
```
And manually delete both the `00LOCK-EpiNow2` file and `EpiNow2` directories. 

I would then manually update rlang, just because it doesn't place nicely. Then go ahead and download EpiNow2 from github.

**Comment by yungwai** [comment]
Hi just wanna report back. I have a few other tries, lastly following the suggestion of @medewitt I installed rlang then I successfully installed the git version of EpiNow2. Running the example now, so far so good. Thanks both!

**Comment by seabbs** [comment]
Great news - sorry you had some issues! 

Just to note we will be shortly moving to a new interface that introduce some breaking changes (detailed here: #102 )

**Comment by yungwai** [comment]
Thanks Sam, will definitely be keeping an eye on the updates. Just in time to hopefully fit to my data :)
