### ISSUE TITLE
Type Mismatch estimate_infections.stan

### ISSUE THREAD

**Issue by medewitt** [epiforecasts/EpiNow2#119]
While working on the cmdstan backend, I got a compilation error for the estimate_infections.stan program on line 153.

```
 R[s] = R[s - 1] .* noise[s - 1];
```
It looks like this is a real * real, so we wouldn't need the vector operator prefix (**.**) on the multiplication operation. Let me know if you agree. RStan might be less strict than cmstan is this regard?

**Comment by jhellewell14** [comment]
I agree, no element-wise multiplication required.

**Comment by medewitt** [comment]
This is fixed in the latest...had a couple of old versions lurking...

**Comment by seabbs** [comment]
Thanks for this @medewitt. 

The fix was introduced when we shifted to doing everything in log space. The plan is to functionalize most of the stan code in the next week or so in order to allow for the addition of more model complexity so picking up these issues is very helpful.

**Comment by medewitt** [comment]
Cheers for the move to logspace--that is awesome. I'll keep my eyes out for other items. Plus CmdStan 2.25 has some additional vectorisation and the option to drop the normalisation constant on the `target+=` arguments. There might also be some within-chain parallelisation opportunities might speed some things up.

**Comment by seabbs** [comment]
Those all sound pretty enticing! At some point, we might be considering fitting multiple time series in a single model and that might be a good case for within-chain parallelization but not there yet.
