### ISSUE TITLE
Summarising runs errors with "Error: `device` must be NULL, a string or a function."

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#130]
For example here https://github.com/epiforecasts/covid-german-forecasts/issues/9

I suspect we need `high_plots$reff` -> `plot` in https://github.com/epiforecasts/EpiNow2/blob/baca6e4f41643ab1f60bb4ce21415e0e629b937d/R/summarise.R#L247

**Comment by seabbs** [comment]
Hot fixed in #6ac60ce - testing locally now on the US forecasting.

**Comment by seabbs** [comment]
Should now be resolved on master.Partially checked in Germany - will close once complete/successful.

**Comment by seabbs** [comment]
Now working as expected on master. Issue with both name and plot passed to inner function `save_ggplot`. Please reopen if not resolved.
