### ISSUE TITLE
logfiles being written into mystery locations

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/EpiNow2#132]
The naming of epinow logs has resulted in those files being written to temporary locations which casues issues from covid-rt-estimates as the logs effectively vanish and don't get off the box.

```
2020-10-20 12:05:16 INFO Producing following optional outputs: regions, summary, samples, plots, latest
Logging threshold set at INFO for the EpiNow2 logger
Writing EpiNow2 logs to: /tmp/RtmpP8FTpS/regional-epinow/2020-10-16.log
Logging threshold set at INFO for the EpiNow2.epinow logger
Writing EpiNow2.epinow logs to: /tmp/RtmpP8FTpS/epinow/2020-10-16.log
Logging threshold set at INFO for the EpiNow2.epinow.estimate_infections logger
Writing EpiNow2.epinow.estimate_infections logs to: /tmp/RtmpP8FTpS/epinow-estimate-infections/2020-10-16.log
```

Whilst I think we can get around this in covid-rt-estimates by initialising the loggers (and the level they should be logging at - in the snippet above the main logger was running at TRACE) this will trip others up.

**Comment by seabbs** [comment]
This shouldn't be the case if logs =NULL as it should default to the next highest log level. Was this the case?

**Comment by seabbs** [comment]
They can't be written to anything other than a temp directory by default unfortunately as this would break CRAN policy.

**Comment by joeHickson** [comment]
ah covid-rt-estimates is not setting the log dir yet!

**Comment by seabbs** [comment]
Ah damn sorry I thought I had set to NULL (and so use your settings) but must have missed.

**Comment by joeHickson** [comment]
Is it part of the v1.2.1 change?

**Comment by seabbs** [comment]
It should be yes.
