### ISSUE TITLE
Allow forecasts to be generated from estimates

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#133]
It would be good to allow R trajectories (or samples thereof) and initial infections as an input that re-simulates infections and reported cases using these trajectories. This would make it possible to, e.g. explore "expert adjustments" to Rt trajectories or scenarios.

**Comment by seabbs** [comment]
Agree also needed for validation work. This so currently managed via the simulate functions code but that is an R implementation that doesn't capture the full model complexity. The Stan refactor (#122) should enable this and as this is the next job on the list may happen fairly quickly.

**Comment by sbfnk** [comment]
Isn't this functionality already provided by `forecast_infections`? It would be more robust for this to be handled stan-internally but it seems the functionality is there.

**Comment by seabbs** [comment]
yes it is (and/or the internal functions).
