### ISSUE TITLE
Return summarised fit diagnostics as default. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#134]
Currently quality of fit diagnostics can only be found by returning the `stan` object and evaluating the fit independently. As flagged by @pearsonca this may be a little difficult when working at scale. It would make sense to provide an "expert" summary of fit diagnostic and return this as standard/optional output from `estimate_infections`, `epinow` etc.

**Comment by pearsonca** [comment]
To be super-picky about it, also needs roxygen `#' @return ...` entry.

Basically, I think it's worthwhile leveraging existing R idiom for functions like `optim` / `optimize` / `deSolve` that provide a variety of simple indicators. While most people ignore those for routine use, they are invaluable when attempting to diagnosis numerical issues. I'm frankly not familiar with what those indicators would be specifically for this algorithm, so clear documentation would go a long way.

aside, a good return object (be it a well defined list or S-whatever-X object) is also much more amenable to engineered handling of issues than warnings / log files / etc. E.g., if there were an option to resume with more samples, would be nice to check the relevant return values for undersampling and trigger resume as appropriate.

**Comment by seabbs** [comment]
totally agree on all points. @joeHickson likely of interest (storing diagnostics as data rather than as a log essentially).
