### ISSUE TITLE
Inconsistency in rstan version requirements

### ISSUE THREAD

**Issue by pcarbo** [epiforecasts/EpiNow2#141]
I noticed in the DESCRIPTION file that two different version requirements are given for `rstan`. It would be helpful if this could be corrected.

Also, if possible, it would be better if you would allow rstan 2.19 to be used; I believe rstan 2.20 or 2.21 introduced a new dependency, `V8`, which requires libraries that are not widely available on all Linux systems. So requiring rstan >= 2.21 may make installation much more difficult for some users.

**Comment by kgostic** [comment]
+1 to the request for compatibility with rstan<2.21. 

Neither my laptop nor my university's cluster has `V8` so I've had to revert to old versions of EpiNow2 to maintain functionality.

**Comment by pcarbo** [comment]
I found a solution, at least one that works for us. For people with this issue, they may try installing the new version of [V8](https://github.com/jeroen/v8) which can be installed without the V8 libraries.

(Regardless, I would fix the rstan version inconsistency in DESCRIPTION.)

**Comment by seabbs** [comment]
Thanks for this @pcarbo and sorry it has caused you both problems. 

I am just looking into when and why this was introduced but on the face of it see no reason it can't be rolled back. Obviously there shouldn't be a an inconsistency so will fix that asap.
