### ISSUE TITLE
Clarify delay parameter inputs in documentation

### ISSUE THREAD

**Issue by kgostic** [epiforecasts/EpiNow2#146]
The documentation for epinow(), estimate_infections(), etc. instruct users to specify the mean and sd of the (lognormal) delay distributions.

I'm often confused by this because it seems to imply that these parameters should be input on an absolute scale, when I think what's actually needed is the "logmean" and "logsd", as defined in the base R documentation for the lognormal distribution family, or "mu" and "sigma", as specified here - https://en.wikipedia.org/wiki/Log-normal_distribution.

From the current documentation, it's also a bit unclear whether "mean_sd" and "sd_sd" are specifed on the log scale.

Thx!

**Comment by seabbs** [comment]
Thanks for this @kgostic, 

your correct it is the logmean and logsd (and logmean_sd etc) - thanks for flagging it. Will look at clarifying (though just thinking about if its worth moving to a gamma for all delays, see #148). Very happy to see a PR if interested.
