### ISSUE TITLE
Convert US forecasts to use EpiNow2

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#16]

**Comment by seabbs** [comment]
@nikosbosse @kathsherratt @sophiemeakin  it would be really great if we could do this before the next forecasting session. I think it makes sense to use a restricted data set (as for the timeseries models) at least initially to speed up fitting. It could also be potentially very cool to fit more than one model. The default is to use a GP to allow Rt to vary over time but could also do a today is like tomorrow static Rt forecast and then ensemble with everything else (using `static = TRUE`). Very happy to talk through how to do this if interested in giving it a go but very unlikely to have time to do it myself as needed to work on the website. `estimate_infections` has examples that go through examples.

**Comment by kathsherratt** [comment]
I have some of this on a branch (albeit in an outdated version of Epinow2) and will pick it up this afternoon. I can spend some limited time on this tomorrow as well. 

I think this will involve (feel free to add):

- [ ] switching Rt code to Epinow2
- [ ] get quantiles and samples in the right format
- [ ] integrate into (at least) mean and QRA ensembling
- [ ] Sunday test run
- [ ] (if time:) set up for fitting more than 1 model; integrate with ensembling

Given this and the need for a full test run before Monday, I think it's maybe less than even odds that we will have this in place for submission on Monday - but I'll do what I can!

**Comment by seabbs** [comment]
Okay- it sounds like to much work (especially given the weekend). I would suggest booting into next week and doing it stress free then. Thanks for picking this up though!

**Comment by seabbs** [comment]
Done
