### ISSUE TITLE
For those looking for estimate_delay()

### ISSUE THREAD

**Issue by philturk** [epiforecasts/EpiNow2#179]
As a cautionary placeholder for others working through this example (README.md), the function `estimate_delay()` is only available in the stable _development_ version of the package using `{drat}`.

**Comment by seabbs** [comment]
Thanks for this @philturk, 

There should be a CRAN update on its way this weekend/early next week so I will close this when the binaries are built. This should be the last major interface breaking change so hopefully this won't be an issue going forwards.

**Comment by philturk** [comment]
> Thanks for this @philturk,
> 
> There should be a CRAN update on its way this weekend/early next week so I will close this when the binaries are built. This should be the last major interface breaking change so hopefully this won't be an issue going forwards.

Thank **you** for a great contribution here!

**Comment by seabbs** [comment]
Closing as `1.3.1` should now be on CRAN with binaries for all platforms in the next 24 hours. Thanks again for opening this. If future breaking changes impact the docs will add a flag.
