### ISSUE TITLE
Example uses of EpiNow2

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#181]
Meta issue to start listing uses of `EpiNow2` for uses vignette. Please add any public uses here either with or without code (but please mark if this is the case). 

- [ Simple example for estimating national level Rt for Covid-19](https://gist.github.com/seabbs/163d0f195892cde685c70473e1f5e867) 
- [Simple example for exploring truncation of input data](https://gist.github.com/seabbs/176b0c7f83eab1a7192a25b28bbd116a) 
- [Estimation framework for multiple data streams at multiple spatial scales](https://github.com/epiforecasts/covid-rt-estimates) and accompanying [website](https://epiforecasts.io/covid/).
- [Covid-19 Germany and Poland Forecasting Hub submission](https://github.com/epiforecasts/covid-german-forecasts/tree/master/rt-forecast)
- [Covid-19 USA Forecasting Hub submission](https://github.com/epiforecasts/covid-us-forecasts/tree/master/rt-forecast-2)
- [Estimating retrospective Rts for Covid-19 on the municipality level in Brazil using Bayesian deconvolution](https://epiforecasts.io/covid-rt-brazil-subregional/). Reproducible code available [here](https://github.com/epiforecasts/covid-rt-brazil-subregional). This repository uses the much faster deconvolution approach in order to make it feasible to estimate Rt on long timescales across many data sets (here 900+) in a still rigorous manner. Real time estimates are likely less accurate than using the default, more compute intensive, method.

**Comment by kathsherratt** [comment]
- [Comparing Rt for England, estimated from cases, admissions, and deaths](https://github.com/epiforecasts/rt-comparison-uk-public), example of running multiple estimates over a long (six month) timeseries, with accompanying [paper](https://www.medrxiv.org/content/10.1101/2020.10.18.20214585v1)
- [Estimating Rt with breakpoints and random walk](https://github.com/epiforecasts/rt-breakpoints), to explore effects of interventions
