### ISSUE TITLE
Initialise `estimate_infections` with a crude fit and then more intensive fit. 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#183]
At the moment `estimate_infections` spends a lot of time in warmup converging towards a relatively small area of the posterior. This appears to be mainly driven by the complexity of fitting the Gaussian process and the lack of informative priors. Potentially doing some kind of small initial fit with very approximate parameters and then feeding this result into a more accurate model fit could help increase performance.

**Comment by pearsonca** [comment]
Not exactly sure what's needed to get the starting conditions, but: does it make sense to start with the crude expected value? As in, take the mean value of all the delays + generation time, smooth series with, say, 7 day ave, and then calculate R based on offset ratios?

**Comment by seabbs** [comment]
So the problem is you would need the posteriors for input parameters used to estimate Rt. I think potentially reparameterising might help.

**Comment by seabbs** [comment]
so as of #185 this now possible with any user supplied fit or with a internal cumulative fit (as may enable some fitting issues to be avoided but this is currently unexplored). The missing feature is that this only updates the initialisation of the model and not the priors which may be a better solution.

**Comment by seabbs** [comment]
Closing as idea outlined is implemented (initialising from a previous fit). Updating priors is flagged in #115 as an outstanding goal.
