### ISSUE TITLE
Review generation times, incubation periods and reporting delays

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#188]
Currently we support a single literature derived incubation period and a single generation time estimate from early in the Covid-19 epidemic. These were motivated at the time but the motivation and degree of interpretation may not be clear to current users.

Potentially these estimates are also slightly out of date with multiple literature reviews having been published recently. It would be sensible to at the very least support multiple options with their citations and potentially update the defaults (though this would need to be clearly flagged to users as will impact estimates). The only limitation here is that at the moment only gamma distributed generation times and log normal incubation periods  are supported but this could be addressed in another issue.

An extension to this would be to add a new function `get_reporting_delay` that contains sensible, either literature derived or approximated, reporting delays to use in examples and potentially for users when data is available. 

Potentially some of this work has been done in other packages and these could instead be linked to with an appropriate converter function (though I have yet to see any options here). 

Pinging @hsbadr as this issue partly motivated by email conversation.

**Comment by seabbs** [comment]
In other work for example I have been using the estimate from Ferretti et al though this doesn't come out the box with uncertainty. 

```
# generation time from: https://www.medrxiv.org/content/10.1101/2020.09.04.20188516v2.full.pdf
# gamma distribution in SI: https://www.medrxiv.org/content/medrxiv/suppl/2020/09/16/2020.09.04.20188516.DC2/2020.09.04.20188516-1.pdf
shape <- 6.8004
rate <- 1.2344
generation_time <- list(mean = shape / rate, 
                        mean_sd = 0.5,
                        sd = sqrt(shape) / rate,
                        sd_sd = 0.25,
                        max = 15)
```

**Comment by sbfnk** [comment]
Uncertainty might be obtainable from the source data/code: https://doi.org/10.5281/zenodo.4033021

**Comment by seabbs** [comment]
Another source that comes to mind is: https://science.sciencemag.org/content/early/2020/11/23/science.abe2424

**Comment by seabbs** [comment]
I had a stab at running the code (successfully but ran out of steam there - it does look doable though once the code has been digested a bit).

**Comment by hsbadr** [comment]
Thanks @seabbs for opening this issue! I still need to understand why/how [your code](https://github.com/seabbs/COVID19/blob/master/MCMC_generation_interval.R) changes the mean generation time to `3.64` days while it's widely accepted at ~`5.2` days, including your reference ([Ganyani et al. 2020](https://doi.org/10.2807/1560-7917.ES.2020.25.17.2000257)).

Here're the estimates I'm currently using from the literature:

```
# Generation time: gamma distribution, with estimates from
# Ganyani et al. 2020 (https://doi.org/10.2807/1560-7917.ES.2020.25.17.2000257)
generation_time <- list(
  mean = 5.2,
  mean_sd = 1.5,
  sd = 2.8,
  sd_sd = 1.5,
  max = 21
)

# Incubation period: log-normal distribution, with estimates from
# McAloon et al. 2020 (https://doi.org/10.1136/bmjopen-2020-039652)
incubation_period = list(
  mean = convert_to_logmean(5.1, 1.65),
  mean_sd = log(1.5),
  sd = convert_to_logsd(5.1, 1.65),
  sd_sd = log(1.5),
  max = 21
)
```

**Comment by seabbs** [comment]
As per email it is based on the Tianjin data and refit using the Lauer et al. incubation period (as required by the Ganyani method). Not committed to this as the default and my preference would be to base that on a literature review estimate (as for the incubation period (though this would then assume independence between the two which is not ideal)). 

Obviously in reality the generation time is likely to be context specific and to change over time though how to choose what it should be in your setting is an open question as far as I am aware.

**Comment by seabbs** [comment]
As per email it is based on the Tianjin data and refit using the Lauer et al. incubation period (as required by the Ganyani method). Not committed to this as the default and my preference would be to base that on a literature review estimate (as for the incubation period (though this would then assume independence between the two which is not ideal)). 

Obviously in reality the generation time is likely to be context specific and to change over time though how to choose what it should be in your setting is an open question as far as I am aware.

**Comment by seabbs** [comment]
Also see issue #140 for additional sources for generation time estimates.
