### ISSUE TITLE
Linux system package use - Non-zero exit status 

### ISSUE THREAD

**Issue by krageth** [epiforecasts/EpiNow2#192]
Upon installing the EpiNow 2 package I am getting the following: EpiNow2 had a non-zero exit status" . I was wondering if there is any way to support this package in a Linux based environment?
![Screen Shot 2020-12-01 at 3 44 51 PM](https://user-images.githubusercontent.com/27814061/100800399-2e7a5680-33ec-11eb-9d2b-f9a8ec61cec4.png)

**Comment by medewitt** [comment]
What OS are you running? Likely some makevars flags need to be set for rstan. Might be worth installing rstan based on their instructions first, then install EpiNow2.

**Comment by krageth** [comment]
I followed this for the initial rstan install:https://github.com/stan-dev/rstan/wiki/Configuring-C-Toolchain-for-Linux

![Screen Shot 2020-12-01 at 3 57 35 PM](https://user-images.githubusercontent.com/27814061/100801688-f247f580-33ed-11eb-9984-edf219b35ad3.png)

My apologies, I am typically working in a windows environment. I am a little novice to Linux

**Comment by medewitt** [comment]
No worries. In the Ubuntu terminal try the following:

```
sudo apt-get update -y && \
    apt-get install -y \
    libudunits2-dev \
    libgdal-dev \
    libqpdf-dev \
    libmagick++-dev \
    && apt-get clean
```

You will likely have to enter your root password. That should ensure that all of the system dependencies are available. Then go into R and try again 

```
remotes::install_github("epiforecasts/EpiNow2")
```

You might have to scroll up through the output to find which (if any) package fails. We can then troubleshoot from there.

**Comment by joeHickson** [comment]
I struggled to get all the pre-requisite packages installed on the locked down linux boxes we have - if you don't get to the bottom of the missing packages then the docker container may be an alternative. I know running linux in linux is a bit overkill but it's got *all* the dependencies pre-installed and you can mount any extra files / code you need in. It is another tool to figure out though.

**Comment by seabbs** [comment]
Thanks @medewitt @joeHickson for jumping in. 

Sorry you are having issues @krageth - feel very free to ping here again if @medewitt suggestions don't help. Once we have gotten to the bottom of this I/we will look at adding more to the wiki on possible install issues. 

Sam

**Comment by krageth** [comment]
I followed @medewitt 's instructions above and I got everything installed. Thank you very much for your help!

**Comment by seabbs** [comment]
Great news!
