### ISSUE TITLE
Remove `src/Makevars*` and review code linting

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#208]
@seabbs Agreed :) You may add the following line at the end of the `configure` script to cleanup all `C++`, `R`, and `Stan` code:
`find . -type f \( -name "*.cc" -o -name "*.h" -o -name "*.R" -o -name "*.stan" \) -exec sed -i 's/[ \t]*$//' {} \;`

BTW. I think we may bring `SystemRequirements: GNU make` back and remove the `src/Makevars*` files to let `rstan`/`rstantools` generate them, since `rstan` may get a major update soon and we don't have to manually update the make files.

_Originally posted by @hsbadr in https://github.com/epiforecasts/EpiNow2/pull/203#issuecomment-744392176_

**Comment by hsbadr** [comment]
@seabbs #209 is ready. It would be great if it gets merged and start development from there. Also, by `rstan` major update, I mean https://github.com/stan-dev/rstan/pull/887, if you'd like to give it a try. I've successfully tested `EpiNow2` + `rstan 2.25` with https://github.com/hsbadr/EpiNow2/commit/5828f95b243abbed4287a5f99d9338862861580a.

**Comment by seabbs** [comment]
Thanks for the PR - great stuff. Also that is a major PR into `rstan`!
