### ISSUE TITLE
Estimation of transition delay distributions from consecutive surveillance time series

### ISSUE THREAD

**Issue by pitmonticone** [epiforecasts/EpiNow2#229]
Hi, 

First of all I would like to thank you very much for the active development of this great package!

Now, suppose you have 

* a pair of consecutive age-stratified surveillance datasets `(primary_incidence, secondary_incidence)` where `primary_incidence` might be the time series of symptomatic cases by date of symptom onset, hospital admission by date of admission or ICU admission by date of admission so that `secondary_incidence` would be the series  of hospital admissions by date of admission, ICU admissions by date of admission or deceased cases by date of death respectively 
* a collection of estimated age-specific transition rates from the literature (e.g. symptomatic fraction, Infection hospitalization ratio, sero-adjusted infection fatality ratio).

Would it be sensible to try to estimate transition delay distributions from `(primary_incidence, secondary_incidence)`? If yes, then what method would you recommend ? Are you thinking about implementing something similar in the near future ?    

Thanks.

**NB**:  I first opened it as a [discussion](https://github.com/epiforecasts/EpiNow2/discussions/226), but then I realised it could be also suited as an issue, so I'll post it here too.

**Comment by seabbs** [comment]
Thanks for this @pitmonticone  and apologies for the slow response I've been working on some other projects to give this room to breath before a fresh dev cycle. 

So I think you could do this with the tools that are implemented if you were willing to categorise age distributions and fit the delay distributions independently (i.e looping through using `estimate_secondary` for each one) and then extracting the fit delay distribution and scaling factor (which you could give a prior from the literature). 

This is actually something we have been thinking about a lot and I have been trying some other approaches (see this [report](https://github.com/epiforecasts/covid19.sgene.utla.rt/blob/main/severity-report.pdf) which is a WIP). That other approach has coalesced into an extension of the `brms` package with a convolution model being implemented as a structural equation model (so you can model covariates on the scaling factor, the distribution mean, and the distribution standard deviation). Its all very very early stage but it is available here (I would use the approach above for now for anything serious whilst I explore this in more detail): https://github.com/epiforecasts/idbrms
