### ISSUE TITLE
Using the option output = "fit" in the regional_epinow function returns only timings

### ISSUE THREAD

**Issue by username-rp** [epiforecasts/EpiNow2#236]
I would like to return the output of the regional_epinow function to a variable, with the option output="fit" specified. However the only thing that is returned are the timings. Please could someone see if they can recreate or is there a solution? Many thanks.
The command I run is:
output <- regional_epinow(reported_cases = cases, 
                       generation_time = generation_time,
                       delays = delay_opts(incubation_period, reporting_delay),
                       rt = rt_opts(prior = list(mean = 1.5, sd = 0.5)),
                       stan = stan_opts(samples = 100, warmup = 200, 
                                        control = list(adapt_delta = 0.95)),
                       verbose = interactive(),
                       target_date = Sys.Date(),
                       return_output = TRUE,
                       output = c("fit","samples","latest"),
                       horizon=0)

**Comment by seabbs** [comment]
Should be fixed
