### ISSUE TITLE
Pipelines failing

### ISSUE THREAD

**Issue by joeHickson** [epiforecasts/EpiNow2#24]
I think there might be a typo error with a repeated incubation_def causing the pipeline to fail

https://github.com/epiforecasts/EpiNow2/blob/642ed239282ffc0ef2606220b904034e58529a99/R/adjust.R#L55

https://github.com/epiforecasts/EpiNow2/runs/865961150#step:10:288

**Comment by seabbs** [comment]
Hi Joe, 

Thanks for this - should now be fixed on master.
