### ISSUE TITLE
parameter `zero_threshold` not documented online

### ISSUE THREAD

**Issue by brynhayder** [epiforecasts/EpiNow2#247]
Seems like the parameter [here](https://github.com/epiforecasts/EpiNow2/blob/bee6bc765f754508da1235466a3388b16a0af812/R/epinow.R#L71) is not documented in the online docs [here](https://epiforecasts.io/EpiNow2/reference/epinow.html).

**Comment by seabbs** [comment]
Hi @brynhayder, 

Thanks for opening this. `zero_threshold` is currently only available in the development version of the package and hence the documentation is provided here: https://epiforecasts.io/EpiNow2/dev/reference/epinow.html

Happy to have suggestions to surface that better. There should be a new release in the next few weeks hopefully to merge this parameter into the released package.

**Comment by brynhayder** [comment]
Thanks for the quick response. Yep, seems like master is not the same as the release I am using! One suggestion is to have the link to source on docs point to the code that creates the release corresponding to the docs, rather than current master. 

In the current release, is there any way to specify this parameter?

Our data has leading zeros for different runs and I think this parameter might be causing the outputs of `epinow` to have different numbers of timesteps.

**Comment by brynhayder** [comment]
@seabbs 

As it happens, I don't think this parameter is what is causing my issue.

I think that [this line](https://github.com/epiforecasts/EpiNow2/blob/17337858796e44f89cd5d2defc690137554a006f/R/create.R#L30) ignores leading 0s in reported cases.
