### ISSUE TITLE
Could regional_summary have an option to turn off plot generation?

### ISSUE THREAD

**Issue by RichardMN** [epiforecasts/EpiNow2#250]
This is a trial balloon for a PR.

My personal use case for EpiNow2 works with @hamishgibbs RtD3 framework using just the CSVs generated by `regional_summary`. I delete the generated graphs (sorry), when I remember to clean up. Would it make sense to put in a param to `regional_summary` which adds an additional test at line 278 and skips until line 349 of `summarise.R`?

**Comment by seabbs** [comment]
Yes it definitely would.
