### ISSUE TITLE
How to access non-compiled stan model for computing effective reproduction ratio

### ISSUE THREAD

**Issue by andrybicio** [epiforecasts/EpiNow2#251]
I'm developing a project for a course at university, and I am stuck at computing the effective ratio Rt. Is there a way to access stan raw files that are not compiled yet? Because I cannot see any "*.stan" in the repo.
I have already computed both generation and delay distributions, but I cannot figure out how to properly write the stan files.

**Comment by seabbs** [comment]
See and lower level folders: https://github.com/epiforecasts/EpiNow2/tree/master/inst/stan
