### ISSUE TITLE
Is there any reason to stick to the current `lognormal` prior on the GP length scale? 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#255]
@seabbs Is there any reason to stick to the current `lognormal` prior on the GP length scale? I get better stability with inverse Gamma (check [this](https://betanalpha.github.io/assets/case_studies/gp_part3/part3.html)), especially with long simulations, and discarding the `ls_mean` & `ls_sd` in `gp_opts()`.
```bash
# Use inverse-gamma prior on Gaussian process (GP) length-scale parameter
sed -i 's|rho ~ lognormal(ls_meanlog, ls_sdlog)|rho ~ inv_gamma(1.499007, 0.057277 * ls_max)|g' inst/stan/functions/gaussian_process.stan

_Originally posted by @hsbadr in https://github.com/epiforecasts/EpiNow2/issues/253#issuecomment-853911207_

**Comment by seabbs** [comment]
thanks for the mini-review @hsbadr 

On your point about the length scale prior. No there is no need to stick to log normal. We went with it at the time as on simulations it worked well and it was easier to parameterise for non-expert users. Having said that since then I have only been using inverse gamma in other projects (i.e here: https://github.com/seabbs/inc2prev/blob/c293db869401f0aedc4d35a5e8a195dda54196ab/stan/model.stan#L65) So very open to moving back to inverse gamma. The key is that it is easy for users to spec.

**Comment by hsbadr** [comment]
@seabbs Sounds good. I'll submit a PR for this.
