### ISSUE TITLE
Better examples in helpfiles for country_map and global_map

### ISSUE THREAD

**Issue by ellisp** [epiforecasts/EpiNow2#29]
At the moment these helpfiles are minimal. I'd be happy to do a more illustrative example if you're up for pull requests.

**Comment by seabbs** [comment]
Hi @ellisp, 

Agree. That would be great. The limitation has been lack of time - not lack of interest!

Sam

**Comment by seabbs** [comment]
Thanks for the PR fixing this - great help!
