### ISSUE TITLE
Distinguish between imported and local cases

### ISSUE THREAD

**Issue by ellisp** [epiforecasts/EpiNow2#30]
This package's predecessor EpiNow could distinguish the `import_status` of cases between local and imported. Is this something that is already feasible with EpiNow2 and I have just missed how to do it? If not, is it a possible enhancement for the future?

**Comment by seabbs** [comment]
Hi @ellisp, 

Thanks for flagging and your correct that this is functionality we have currently lost. We think the new method offers enough benefits (i.e better reconstruction of the infection curve and therefore improved R estimates) to make this trade-off worthwhile in the short term given the caseload in many parts of the world (obviously this is not the case everywhere). 

The plan is to definitely add this is in at a later date but this requires a bit of thought. Good to know this is a feature of current interest - definitely helps when deciding priorities.

**Comment by seabbs** [comment]
Closing as discussion moved to #39
