### ISSUE TITLE
Add input validation

### ISSUE THREAD

**Issue by Bisaloo** [epiforecasts/EpiNow2#337]
I think many errors (both in my own usage and in some bug reports such as #267) seem to come from invalid input. 

I understand that what constitutes a valid input is documented but I believe some extra hand-holding by failing early with clear error messages on invalid input would go a long way in helping users.

A main topic to discuss is probably what would be the best framework to do this input checking. Some options are presented in [the 'Checking the inputs of your R functions' blog post](https://blog.r-hub.io/2022/03/10/input-checking/).

**Comment by sbfnk** [comment]
One thing perhaps to do is for every of the `..._opts` functions in https://github.com/epiforecasts/EpiNow2/blob/main/R/opts.R that are used to passed options to `estimate_infections` in https://github.com/epiforecasts/EpiNow2/blob/dd484e2b25daa80f03124ab63890a970c05d8c38/R/estimate_infections.R#L220 to return their own S3 class. We could then check in `estimate_infections` that the arguments are of that class, avoiding instances where this is confused as e.g. in https://github.com/epiforecasts/EpiNow2/blob/dd484e2b25daa80f03124ab63890a970c05d8c38/tests/testthat/test-epinow.R#L101.

**Comment by jamesmbaazam** [comment]
@seabbs I would like to take a stab at this. Please assign me.

**Comment by seabbs** [comment]
Awesome - looking forward to seeing what you come up with. Make sure to target the `develop` branch with your changes vs `main`.

**Comment by sbfnk** [comment]
There is no more `develop` branch so you can target `main` directly when taking this on.

**Comment by jamesmbaazam** [comment]
Noted.

**Comment by jamesmbaazam** [comment]
Sorry it took a while to get to this but I am going to start working on it this week. Will push some changes by close of Friday.
