### ISSUE TITLE
Fix StanHeaders dependency

### ISSUE THREAD

**Issue by pcarbo** [epiforecasts/EpiNow2#34]
I think the StanHeaders dependency in `DESCRIPTION` needs to be updated. I had StanHeaders version 2.21.0-3 installed, and I got an error about a missing header file. It worked when I upgraded StanHeaders to the latest version (2.21.0-5).

**Comment by seabbs** [comment]
Thanks for this @pcarbo, 

I'll check this out locally and see if I can reproduce but a version issue sounds likely. 

What operating system was this on btw?

**Comment by pcarbo** [comment]
Hi  @seabbs here is my sessionInfo:

```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.4 (Nitrogen)

Matrix products: default
BLAS/LAPACK: /software/openblas-0.2.19-el7-x86_64/lib/libopenblas_haswellp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.0
```

**Comment by seabbs** [comment]
Thanks @pcarbo, 

Checked this out and it looks like updating the StanHeaders version has fixed this. Let me know if not the case and happy to reopen.

**Comment by pcarbo** [comment]
Looks great, thanks!
