### ISSUE TITLE
Problem with distribution parameters

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#344]
At the moment in the `develop` branch there's a problem that for the lognormal the `*_mean` parameters are [interpreted as the `mu` parameter of the lognormal](https://github.com/epiforecasts/EpiNow2/blob/f911647ef7a1e7c5f755f72dab0d73c70e81cb1c/inst/stan/functions/pmfs.stan#L13) (i.e. not the mean) whereas for the gamma they are "correctly" [interpreted as means](https://github.com/epiforecasts/EpiNow2/blob/f911647ef7a1e7c5f755f72dab0d73c70e81cb1c/inst/stan/functions/pmfs.stan#L16). This means we can't consistently bound them and as the gamma means need to be >0 but lognormal mu can be any real. As things are this can lead to an error when using the gamma.

I think the best solution to that problem that is clear to the user might be to allow passing e.g. `mean` or `median` to [`delay_dist`](https://github.com/epiforecasts/EpiNow2/blob/f911647ef7a1e7c5f755f72dab0d73c70e81cb1c/R/dist.R#L739), interpret them as true means and medians and do all the conversion to logmeans etc. internally - the stan model would then only see the log means which can be unbounded.

**Comment by seabbs** [comment]
Ah okay, that makes sense. 

So the core issue with doing internal transformation is that what do you do when distributions have uncertainty? In that instance we really need the input parameters to be the same as those commonly output by people estimating delays. We also want these parameters to be as uncorrelated as possible so that our assumption of independence for the priors is less far off.

**Comment by sbfnk** [comment]
> So the core issue with doing internal transformation is that what do you do when distributions have uncertainty? In that instance we really need the input parameters to be the same as those commonly output by people estimating delays. We also want these parameters to be as uncorrelated as possible so that our assumption of independence for the priors is less far of.

That makes complete sense but isn't this already an issue because people usually report mean or median and variance each with some marginal uncertainty / confidence intervals (if any uncertainty)? I'm not convinced the assumption of independence is usually justified (though of course replacing them with some arbitrary correlation introduced by a transformation isn't great either). The issue you mention already affects e.g. transforming mean/variance to lognormal parameters, right?

Perhaps a solution combining the two approaches could be to allow the user to specify either distributional parameters (logmean/logsd or alpha/beta) or summary statistics (mean/median/var) but throw a warning in case of the latter?

**Comment by seabbs** [comment]
> Perhaps a solution combining the two approaches could be to allow the user to specify either distributional parameters (logmean/logsd or alpha/beta) or summary statistics (mean/median/var) but throw a warning in case of the latter?

This is an option we can explore. I think for now the pragmatic solution is to use the type of dist passed to add a bound on the mu/mean etc parameter. This will resolve the immediate issue and can then look at above as a future feature extension.

**Comment by seabbs** [comment]
Sadly vectorsed lower bounds are not implemented in the version of stan that `rstan` supports so the approach to this needs a rethink.

**Comment by seabbs** [comment]
I've sort to get around this by properly truncating the priors and otherwise relying on the `_cdf` functions to handle rejecting impossible values. Testing this now.

**Comment by seabbs** [comment]
After some limited testing this approach does seem to just "work" though there may be more issues if delays are very short and uncertain.

**Comment by seabbs** [comment]
Happy to close this out? It certainly isn't ideal. Perhaps we should open another issue outlining your desired hybrid interface for natural scale mean and sd across parameters?

**Comment by sbfnk** [comment]
Yes can close as the immediate error is resolved. But I also agree we really need to consider the interface and probably flag to the user somewhere (or perhaps it's already there) that the `mean` argument to the distributions means something different for lognormal and gamma now that they're specified with a common interface - discussing in a separate issue sounds good to me.
