### ISSUE TITLE
Update to use `dist_spec` as a common distribution specification device.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#357]
Yes agree on all of these. Perhaps a half way house would be to bring the _opts functions back but have all of them take an S3 delay_dist object as first argument? The post processing of e.g. delays could then move back into these functions. This would also remove the need for dot arguments anywhere (as we can specify multiple delays with the c function).

_Originally posted by @sbfnk in https://github.com/epiforecasts/EpiNow2/issues/343#issuecomment-1406305408_

**Comment by sbfnk** [comment]
Addressed in #363
