### ISSUE TITLE
Clarify documentation for passing uncertainty from estimate_truncation to estimate_infections

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#367]
See https://github.com/epiforecasts/EpiNow2/discussions/365 for a user question highlighting the current issues and explanations of the current functionality. Ideally, we would improve areas of the documentation to make the various options clearer. This likely needs to happen both in the function examples and also with an explicit vignette walking through some of the more commonly used workflows we support.

**Comment by jamesmbaazam** [comment]
This issue has been partly addressed in the "truncation" section of the workflow vignette introduced in #458 (https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections_workflow.html#truncation). However, reading it from the user perspective, I think, where it says "...which returns, amongst others, posterior estimates of the truncation distribution", we can explicitly say which output from `estimate_truncation()` is relevant here. In this case, it's `dist`.

We can also clarify in the documentation of the `truncation` argument of `estimate_infection()` and `estimate_secondary()` that it can be supplied as the `dist` output of `estimate_truncation()` and possibly link the relevant section in the workflow vignette.

**Comment by sbfnk** [comment]
@jamesmbaazam do you think there is anything else we should do here for the upcoming release?

**Comment by jamesmbaazam** [comment]
I'm cleaning up a few docs here and there to see if it clarifies this. PR incoming soon.
