### ISSUE TITLE
Touchstone set up

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#369]
touchstone now works - [this](https://github.com/epiforecasts/EpiNow2/pull/366#issuecomment-1426104231) is with a fixed seed and `n=1` which may or may not be what we want. Alternative would be to increase `n` but overall runtimes will increase rapidly and avoiding MCMC stochasticity by setting the seed might be a good thing.

The linked PR should not affect runtimes at all so the shown changes give an indication of hardware runtime stochasticity.

**Comment by seabbs** [comment]
Nice! 🥳 

I think we might want to increase n so we have some idea if runtimes differences are meaningful or not? Even with seeds set etc there is a few seconds difference on the test PR which I think is just noise.

**Comment by sbfnk** [comment]
Yes we had 40 mins ([n=1](https://github.com/epiforecasts/EpiNow2/actions/runs/4150970081/jobs/7180968592)) vs 2h ([n=5](https://github.com/epiforecasts/EpiNow2/actions/runs/4151207531/jobs/7181356325)). As you say probably not an issue in the grand scheme of things.
