### ISSUE TITLE
Update installation information; suggest `pak`

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#376]
The instruction to use `install.packages(...)` is faulty and either doesn't work because the package has been archived on CRAN or messes up with the dependency installation when installed from epiforecasts.

I would suggest updating the README to use `pak::pkg_install('epiforecasts/EpiNow2')`.

I could submit a PR to close this.

**Comment by seabbs** [comment]
> The instruction to use install.packages(...) is faulty and either doesn't work because the package has been archived on CRAN or messes up with the dependency installation when installed from epiforecasts.

Thanks James. See #372 

> I would suggest updating the README to use pak::pkg_install('epiforecasts/EpiNow2').

Why `pak`? 

> I could submit a PR to close this.

We are just about to go back to CRAN so first point doesn't need changing. Depending on reasons for `pak` that could be really helpful.

**Comment by jamesmbaazam** [comment]
> Why pak?

`EpiNow2` currently has over 72 dependencies, some of which require compilation (run `pak::pkg_deps("epiforecasts/EpiNow2")`. 

`pak` resolves and auto-installs the dependencies in parallel and I think this could save the user some time. 

I also like that it unlocks `dll` files in Windows as this can be problematic sometimes and might require you to restart R or R Studio.

More features [here](https://pak.r-lib.org/dev/reference/features.html).

**Comment by jamesmbaazam** [comment]
What kinds of bugs have you encountered? 

It's been a pleasant experience for me.

**Comment by seabbs** [comment]
Repeatedly failing to work, failing to find dependencies and giving cryptic errors, hanging without erroring

**Comment by seabbs** [comment]
That was a while ago so perhaps things have moved on. Have you tested the `EpiNow2` installation suggested here (and on which platforms)?

**Comment by jamesmbaazam** [comment]
> Repeatedly failing to work, failing to find dependencies and giving cryptic errors, hanging without erroring

I haven't experienced any of these recently. I will dig into the issues/PRs if that's necessary to help set up an installation instruction using `pak`.

> Have you tested the EpiNow2 installation suggested here (and on which platforms)?

Worked fine on Windows but failed on Mac. On the latter, it installed all the dependencies but failed to compile `EpiNow2`. It's a new Macbook so I probably have to install some of the missing [MacOS system dependencies for compiling the packages](https://cran.r-project.org/bin/macosx/tools/), etc.

**Comment by seabbs** [comment]
I'm still not sure we need to mandate this to users. I'm happy to hear from others to tip the balance though. 

What does dplyr dovis always a good q?

**Comment by seabbs** [comment]
And they are using pak... That is enough if a scales tip for me. Happy to see a PR for this.

**Comment by jamesmbaazam** [comment]
Happy to submit a PR. We could suggest it in addition to `remotes`. What do you think?

**Comment by seabbs** [comment]
sure
