### ISSUE TITLE
Use of nested `ifelse`

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#379]
The current code base has multiple instances of nested `ifelse` usage. These would be easier to manage if switched over to using `data.table::fcase()`.

**Comment by athowes** [comment]
I've used [`dplyr::case_when`](https://dplyr.tidyverse.org/reference/case_when.html) for this before, works well.

**Comment by jamesmbaazam** [comment]
`dplyr::case_when()` is a good alternative, however, this package already imports `data.table`, so might as well use it extensively.

**Comment by jamesmbaazam** [comment]
I am currently working on this issue in the linked draft PR, which I'll release for review when done. Touchstone is reporting some minor gains in speed and I guess that's a good thing if the gains add up substantially.
