### ISSUE TITLE
Replacing superceded/deprecated functions

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#384]
I would like to know what the plan is for superseded and/or deprecated imported functions. 

Do you prefer to leave them as is because they are not causing any bugs or unexpected behaviors or would you prefer to import their replacements? An example is the use of `purrr::transpose()` in multiple functions in `dist.R`. `purrr::transpose()` has been replaced by `purrr::list_transpose()`. 

Not necessarily a priority but I would be happy to refactor in a future PR.

**Comment by jamesmbaazam** [comment]
@seabbs I think this might be better placed under Q&A of the discussions tab.

**Comment by seabbs** [comment]
No worries. Yes we want to drop the use of depreciated functions and use their replacements. Very happy to have a PR

**Comment by jamesmbaazam** [comment]
I've started working on this PR and will submit it soon after some checks.

**Comment by seabbs** [comment]
In this PR can you bump yourself from ctb to aut please so we don't forget later!

**Comment by jamesmbaazam** [comment]
Sure thing!
