### ISSUE TITLE
Edge case breaking summary stats output

### ISSUE THREAD

**Issue by jrcpulliam** [epiforecasts/EpiNow2#392]
When both the upper and lower bound of the latest estimate are 0, log_cases is set to NA in [summarise.R](https://github.com/epiforecasts/EpiNow2/blob/main/R/summarise.R) (lines 311-312; 0/0 > 1000 returns NA, instead of a logical). 

This produces an error when generating summary statistics: "Error in if (log_cases) {: missing value where TRUE/FALSE needed"

**Comment by seabbs** [comment]
Thanks @jrcpulliam for reporting.

That does sound like an edge case we haven't considered. Will get on fixing that!
