### ISSUE TITLE
reduce number of models to be compiled

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#393]
Installing the package from source takes quite a long time, partly due to the number of models being compiled. At the very least, the `exp`, `lnorm` and `gamma` models used by `dist_fit` could be combined, and `tune_inv_gamma` (which I don't think is used any more) be removed.

**Comment by seabbs** [comment]
> exp, lnorm and gamma models used by dist_fit could be combined, 

This can be done with no impact to users

> nd tune_inv_gamma (which I don't think

This needs a careful check as I am not so sure and then likely needs depreciation for a minor version.

**Comment by sbfnk** [comment]
>  I am happy to take this on as part of a general revamp of estimate_delays

Ah sorry only just saw this. Revamp still needed obviously.

**Comment by seabbs** [comment]
Yes, it could be pulled out. It depends on the utility of lots of packages vs a single package workflow which needs input from users really unless it offers really clear advantages. 

I will expand on your changes once finalised to add some more recent work. These will be breaking changes so good to do after your update is merged.

**Comment by seabbs** [comment]
The logical thing to do might be to focus on functionality in the first instance (from me/you) and then maybe can move to someone else for porting into its own package infra if desired.

**Comment by seabbs** [comment]
sommething to note is that if wanting a latent delay in the model then it would start want to have functionality from the rest of the package.

**Comment by seabbs** [comment]
or a mixture of distributions etc.

**Comment by sbfnk** [comment]
I'm totally not opposed to keeping it in - I think there are good arguments for and against. My main gripe is the amount of compile time which can be a barrier to effective development (but could of course be lived with if the arguments to keep it in are stronger).
