### ISSUE TITLE
Trigger touchstone only when stan model is changed?

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#399]
We're currently wasting a lot of computation in benchmarking irrelevant changes to the code. We could consider only triggering touchstone when the stan model is changed (additionally perhaps when touchstone itself is changed), given that it will determine the vast majority of run time. This could be implemented by providing a more refined set of paths here:
https://github.com/epiforecasts/EpiNow2/blob/dee8c4f7a438553b44c9b187728e8c9075342305/.github/workflows/touchstone-receive.yaml#L10

**Comment by seabbs** [comment]
Yes good idea, it will likely lead to some edge cases slipping through but hopefully not many. If we leave/add manual triggering as an option that should cover most other cases where we know changes might impact the benchmarks.
