### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#403]
Stan supports optimisation for point estimates. This might be a nice feature to add (with appropriate caveats returned to the user).

**Comment by sbfnk** [comment]
A better option might be to use the laplace approximation within the cmdstanr backend. This will add at least approximate uncertainty.

**Comment by seabbs** [comment]
or wait a bit and just support pathfinder

**Comment by sbfnk** [comment]
or not wait as we can use it in the cmdstanr backend? (just finishing local tests, PR forthcoming)
