### ISSUE TITLE
Discretisation

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#411]
The current discretisation of delay distributions integrates between integer boundaries [0, 1], [1, 2], ...

Recent work has shown that this leads to bias. A better option would be to discretise as [0, 1], [0, 2], [1, 3], ...

**Comment by seabbs** [comment]
* Relative to the underlying continuous distribution that may be used as a prior.

**Comment by jamesmbaazam** [comment]
Can you link some of the recent work here?

**Comment by seabbs** [comment]
https://github.com/epinowcast/epinowcast/blob/05b4f64be8ecb5f319c4cffb970698e91434c3a5/inst/stan/functions/discretised_logit_hazard.stan#L35 and see the package docs for the maths behind it.

**Comment by jamesmbaazam** [comment]
Thanks, Sam. I'll take a look.
