### ISSUE TITLE
Failing tests on Windows

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#420]
A test is currently failing on Windows. It is not clear what has caused this, and it does not seem to be linked to the latest PR #416 (as it also happens without its main change): https://github.com/epiforecasts/EpiNow2/actions/runs/5554848587/jobs/10147747916?pr=419

**Comment by seabbs** [comment]
Note that we saw some instability in performance when updating the delay handling code that could be related to this.

**Comment by sbfnk** [comment]
This now also happens on [older version of the code](#421) suggesting that it has to do with windows-specific updates to the GHA.

**Comment by seabbs** [comment]
well that is good news and also I suppose bad newa

**Comment by sbfnk** [comment]
I'm not completely convinced the problem is in estimate_secondary as the fitting failures occur on all platforms. Something strange is happening sometimes on windows which may be unrelated
https://github.com/epiforecasts/EpiNow2/actions/runs/5577074428/jobs/10190215287?pr=418#step:6:554

**Comment by seabbs** [comment]
That seems very possible though far from ideal

**Comment by sbfnk** [comment]
In summary, this seems to happen intermittently and at various stages of testing (#418) on current as well as previous versions of EpiNow2 (#421) and with current and older versions of StanHeaders (#427). It's not clear what distinguishes these runs from the ones running successfully on macOS.

**Comment by sbfnk** [comment]
This seems to have resolved itself without any code change.
