### ISSUE TITLE
Intermittent segfaults on Ubuntu

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#428]
Seeing the `R CMD check` action sometimes failing during garbage cleaning on Ubuntu with a segmentation fault. This happens with current and older (#421) versions of EpiNow2 as well as with current and older (#427) versions of StanHeaders:

Example outut:
```
    *** caught segfault ***
  address 0x55ec00000004, cause 'memory not mapped'
  
  Traceback:
   1: gc()
   2: showConnections()
   3: cleanEx()
  An irrecoverable exception occurred. R is aborting now ...
  Segmentation fault (core dumped)
```

**Comment by seabbs** [comment]
Do you think this is memory related?

**Comment by sbfnk** [comment]
It certainly looks like it - though not clear to me at all what exactly the issue is.

**Comment by sbfnk** [comment]
This seems to have resolved itself without any code change.
