### ISSUE TITLE
Long example run times

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#430]
Some of the examples have very long run times - especially the ones for `estimate_infections` which run a number of model variants that take about an hour on github actions. It might be good to keep this to a single example and move the variants to a vignette explaining/showing differences and possible advantages/disadvantages.

**Comment by seabbs** [comment]
Needs to be clearly signposted (heard from multiple people that haven't found the examples historically) but could be a good idea.

**Comment by sbfnk** [comment]
These are the example runtimes (in minutes) reported for each example that take >10 seconds on windows:

```
name                       elapsed
   <chr>                        <dbl>
 1 estimate_infections         50.5  
 2 regional_epinow             21.2  
 3 plot_estimates               4.70 
 4 epinow                       3.44 
 5 regional_runtimes            3.43 
 6 simulate_infections          2.72 
 7 estimate_delay               2.68 
 8 get_regional_results         2.58 
 9 regional_summary             2.11 
10 bootstrapped_dist_fit        2.07 
11 report_plots                 1.62 
12 estimate_secondary           0.459
13 dist_fit                     0.405
14 sample_approx_dist           0.369
15 adjust_infection_to_report   0.199
```

**Comment by seabbs** [comment]
Just to note that the examples have long run times because the models in the package have long run times. I think focussing on the latter would be better than focussing on the former. I am also not clear that people typically run a lot of examples from a single function? I would typically read through and then pull out the example I was interested in.

**Comment by sbfnk** [comment]
Yes possibly - main issue with all these examples is the long `R CMD CHECK`.

**Comment by seabbs** [comment]
The obvious thing to avoid running at all costs as an example is `regional_epinow`. Shouldn't those and `estimate_infections()` already be skipped in the CMD check?

**Comment by sbfnk** [comment]
Isn't that only the case when running with `--as-cran`? And even that [no longer](https://community.rstudio.com/t/r-cmd-check-r-4-0-0-now-runs-donttest-how-to-proceed-with-long-running-examples/64493) as of R 4.0.0 (though could possibly replace with `dontrun` to skip them when run with `--as-cran`).

**Comment by seabbs** [comment]
🤷🏻 I would describe myself as unsuree.
