### ISSUE TITLE
Error in regional_epinow function?

### ISSUE THREAD

**Issue by sophie-schiller** [epiforecasts/EpiNow2#44]
I recently downloaded the development version and get a
``` 'list' object cannot be coerced to type 'double'``` error from regional_epinow.

I believe this arises from the following test on regional_errors (regional_errors is a list of NULLs if there are no errors). 

```r
  if (length(regional_errors != 0)) {
    message("Runtime errors caught: ")
    print(regional_errors)
  }
```

**Comment by seabbs** [comment]
Hi @sophie-schiller,

Thanks for this - good spot. 

Looks like there was a rushed ) from a rushed implementation. Should be fixed now on master.
