### ISSUE TITLE
Add workflow to sync citation file with DESCRIPTION.

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#466]
Would be good to add the workflow to keep the citation file in sync with changes in the DESCRIPTION file. This can be fixed by running `cffr::cff_gha_update()`.

**Comment by seabbs** [comment]
See @Bisaloo comment here https://github.com/epiforecasts/EpiNow2/pull/467#issuecomment-1757753822 for a suggested approach to resolve this.
