### ISSUE TITLE
Testing using rstan develop branch

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#471]
Current testing is using the rstan develop branch as it would otherwise fail due to an error in the CRAN version.

Corresponding changes are in https://github.com/epiforecasts/EpiNow2/pull/470 and marked with the string "once rstan is updated on CRAN".

**Comment by seabbs** [comment]
Sorry to be clear there is an error in the CRAN version of R stan that is causing the `GitHub` version of `EpiNow2` to be broken? Or is the CRAN version also broken?

**Comment by sbfnk** [comment]
> Sorry to be clear there is an error in the CRAN version of R stan that is causing the GitHub version of EpiNow2 to be broken?

This (only breaks testing not functionality though). The error is fixed in `develop` of rstan which will eventually go on CRAN.

**Comment by seabbs** [comment]
Ty. Which part of testing? I have a few users with hard to explain bugs so just wondering if there is something here.

**Comment by sbfnk** [comment]
It's exposing stan functions of the `_lp` type. Can't imagine that will make a difference to any user.

https://github.com/stan-dev/rstan/issues/1093
https://github.com/stan-dev/rstan/issues/1098

**Comment by seabbs** [comment]
No agree. Oh dear - back to the drawing board

**Comment by seabbs** [comment]
Also wow that regex.

**Comment by sbfnk** [comment]
This is now on CRAN so can be reverted.
