### ISSUE TITLE
Fix partial matching of `dist` to `distribution` in `get_generation_time()`

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#473]
I know that `get_generation_time()` is to be deprecated according to #390, but currently there is an issue with partial matching resulting from its call to `dist_spec()` which expects `distribution` instead of `dist`. I only noticed this because I've set up my R profile to warn on partial match. Here's a reprex.

```r
options(warnPartialMatchArgs = TRUE)

library(EpiNow2)
generation_time <- get_generation_time(
  disease = "SARS-CoV-2",
  source = "ganyani",
  max_value = 15
  )
#> Warning in (function (mean, sd = 0, mean_sd = 0, sd_sd = 0, distribution =
#> c("lognormal", : partial argument match of 'dist' to 'distribution'
generation_time
#> 
#>   Uncertain gamma distribution with (untruncated) mean 3.6 (SD 0.71) and SD 3.1 (SD 0.77)
Created on 2023-10-12 with [reprex v2.0.2](https://reprex.tidyverse.org/)
```

**Comment by jamesmbaazam** [comment]
The same goes for `get_incubation_period()`

**Comment by sbfnk** [comment]
Thank you. A PR would be welcome as this function will continue to exist for a while even after becoming deprecated.

**Comment by seabbs** [comment]
Good catch.  `options(warnPartialMatchArgs = TRUE)` having this in your Rprofile is a good idea!

**Comment by jamesmbaazam** [comment]
We could add it to the testing setup like this https://github.com/epiverse-trace/packagetemplate/blob/main/tests/testthat/setup-options.R.
