### ISSUE TITLE
Option for cmdstanr?

### ISSUE THREAD

**Issue by medewitt** [epiforecasts/EpiNow2#48]
Just a general question. I built a fork using [cmdstanr](https://mc-stan.org/cmdstanr/) which should be extensible and avoid some of the rstan issues in the future. Downside is that cmdstanr isn't (yet) on CRAN and it adds an external system requirement for cmdstan. I don't know if there is interest, but I could update my code and include cmstanr as an option. It could be an argument to `estimate_infections`

```
 use_cmdstan = FALSE # in arguments
```

Then in body of function:

```
if (use_cmdstan){
    
    if(is.null(model)){
      model <- system.file("stan", "estimate_infections.stan", package = "EpiNow2")
    }
    
    #stan_file <- here::here("inst", "stan", "estimate_infections.stan")
    
    mod <- cmdstanr::cmdstan_model(model, compile = TRUE)
    
    if (verbose) {
      message(paste0("Running for ", samples," samples (across ", chains, 
                     " chains each with a warm up of ", warmup, " iterations each) and ",
                     data$t," time steps of which ", horizon, " are a forecast"))
    }
    
    if(is.null(threads_per_chain)){
      threads_per_chain <- 1L
    }
    
    cmdfit <- mod$sample(data = data, chains = chains,
                      parallel_chains = cores,
                      init = init_fun, iter_warmup = warmup,
                      iter_sampling =  ceiling(samples / chains), 
                      max_treedepth = max_treedepth,
                      threads_per_chain = threads_per_chain,
                      adapt_delta = adapt_delta,
                      refresh = ifelse(verbose, 50, 0),
                      save_warmup = debug)
    
    fit <- rstan::read_stan_csv(cmdfit$output_files())
```
 I don't know how much IO time could add, but I have been finding cmdstanr is more stable.

**Comment by seabbs** [comment]
Hi @medewitt , 

This is a nice idea and there are certainly some features of the latest Stan I would like to experiment with. Could this be added and keep the package CRAN compliant/without cmdstanr as a dep. If so seems like it could be a nice addition for dev work/advanced users. 

Sam

**Comment by seabbs** [comment]
P.S I think the expectation should be the user passes in a compiled model rather than compiling in the function otherwise when running over multiple regions etc you would end up wasting a lot of compute time redoing the compilation.

**Comment by seabbs** [comment]
Hi @medewitt, 

Just pinging to see if there is still interest in this?

**Comment by medewitt** [comment]
Hi @seabbs , 

Yep, I'm still interested. I don't know if it would be easier to make a separate mirror package that drops the rstan dependencies and uses cmdstanr (and won't be on CRAN or a while) or to add the optional argument and add cmdstanr as a suggests. Totally open to whatever direction you suggest. 

Let me know your thoughts and I can start working!

**Comment by seabbs** [comment]
Awesome! 

Hmm, I would guess adding as an optional argument would be better long term but not sure we would then be able to push to CRAN? 

I would have thought a mirror package might be quite a bit of work to keep in sync etc and potentially won't get found by people. 

Perhaps part of `estimate_infections` can be made to use an optional passed in function (which could then call `cmdstanr`). Not sure that is the best idea either though. Open to suggestions!

**Comment by medewitt** [comment]
Good new... the brms package can serve as an example. We could include cmdstanr as a suggests, then add an argument for `stan_args` to accept "backend" which can be one of rstan or cmdstanr. That keeps everything CRAN compliant.

I might fork a branch for EpiNow2lite or something like this in order to test reducing the rstan dependencies (only because I spent  way too much time playing with Makevars each time I set-up a new machine).

**Comment by seabbs** [comment]
That is good news! Do suggests also have to be on CRAN or am I misremembering that? Sounds like a great approach though. - keen to see what comes of it.

**Comment by medewitt** [comment]
@seabbs, it looks like suggests don't have to be on CRAN, it will just be another `requireNamespace` that we can fail gracefully if not installed (brms looks to do this). I found a few examples of this, so we should be good to go.

Here's my deployment strategy in several functions 

- [ ]  add a `backend = c("rstan", "cmdstanr")` argument to `estimate_infections`  in order to select the backend used
- [ ]  `initialise_cmdstan_model` which will initialise/compile cmdstan model object if not already compiled. If no model argument is passed, the the default in forecast infections will be compiled and the executable will be place in the app directory (would require [appdirs](https://cran.r-project.org/web/packages/rappdirs/index.html) dependency to help make sure that the executable is placed in the right location. Not keen on more deps, but I don't see a good argument in the case where the user doesn't want to write their own model). The wonder of cmdstanr is that this compilation only takes place once, so it won't be compiled each function call, only once during package installation.
- [ ]  `create_stancmd_args` which will be a mirror for `create_stan_args` to map the arguments to cmdstan. Unfortunately, the arguments between rstan and cmdstanr are slightly different format/syntax, but that can be easily handled. This would handle NUTS and VB.
- [ ] `fit_cmdstan_nuts`/`fit_cmdstan_vb` which will add in the logging, future.apply, and timeout steps mirroring the other functions and converting the output to an rstan object so the downstream functions will remain unchanged. 

There are some slick things that cmdstanr does regarding writing the samples to csv that could be considered later. 

Thoughts? Am I missing anything?

**Comment by seabbs** [comment]
Ah, that is great news. 

This all looks very sensible and I think you have covered all the bases. The replication of the `fit_` functions is a bit of a shame as that may be quite tedious but I am not sure there will be easy ways to share code there.

**Comment by medewitt** [comment]
@seabbs , I have a candidate for this now. Do you want pulls directly into (master|main) or do you want to create a dev branch that I can send the PR towards?

## Implementation
### Dependencies
Adds:
* cmdstanr to suggests 
* rappdirs to suggests to handle placement of the default Stan programs 
### New Functions
#### Helper Functions
* `safe_dir_create`,`safe_file_copy`, `copy_models` functions that allow for error free copying of the default Stan program to the User's cache. 
*` make_cmdstan_list` which reformats outputs from `create_stan_args` and formats appropriate for cmdstan syntax
* `fit_model_with_nuts_cmd` which has same functionality with `fit_model_with_nuts`, just some internal changes for cmdstan. Could likely move into `fit_model_with_nuts` with some internal flow control.
#### User Facing Changes
`estimate_infection` got two new arguments for `backend` and `cache_model` which default to "rstan" and TRUE respectively. 

### Testing

Locally tested on `estimate_infections`, `epinow`, and `regional_epinow` without error.

Will need to think through how to add these to the testing strategy. We would need to add a step to install cmdstan which might back the tests quite long.

### Outstanding Question
Any advantages in adding alternate backend to the distribution series of functions?

**Comment by seabbs** [comment]
Great news. I've set up a new branch `v.1.3.0` which will hold the next stan focussed package version so a PR on that would be good as `v1.2.0` will be submitted to CRAN shortly so would like to remain as is. 

All sounds good. Testing might be an issue as you say. 

I don't think the distributions series of functions really require an alternative backend as they are really quite light weight and I imagine its more work that its worth. Happy to hear differently.

**Comment by medewitt** [comment]
@seabbs @hsbadr ,sticking this as a reminder - I need to write a function that allows the user to clear the cached executables if they wish.

Something like:

```
clear_epinow_cache <- function(){
requireNamespace('rappdirs')
cache_location <- user_cache_dir("EpiNow2)

lapply(file.list(cache_location), unlink)
message("xyz have been removed")
}
```

**Comment by sbfnk** [comment]
We now have a functional `cmdstanr` branch so adding this as an option should in the way described here should be possible.

**Comment by medewitt** [comment]
Just to put this out there, R >= 4.0 the tools package [has the ability to access package|user cache](https://stat.ethz.ch/R-manual/R-devel/library/tools/html/userdir.html) so `rappdirs` would not be needed. 

Feel free to take anything from [this package](https://github.com/medewitt/staninside) which I wrote in the hopes of one day getting back to this (and ensuring CRAN compliance).  The models would be compiled in the user package directory each package version on first use. When the user updates the package version, the cache will be cleared.

**Comment by sbfnk** [comment]
Now that `rstan` has been brought up to date we can at the very least have an option for running `cmdstan` as the stan model is no longer different.

**Comment by seabbs** [comment]
If we convert out to `rstan` after fitting this should all be quite doable I would think by just supplying a new `fit_opts` wrapper.

**Comment by sbfnk** [comment]
It's already all implemented and functional in the [`cmdstan` branch](https://github.com/epiforecasts/EpiNow2/tree/cmdstanr), would just need a few if/else statements and polishing.

**Comment by seabbs** [comment]
Did you do that by updating the current fitting functions (https://github.com/epiforecasts/EpiNow2/blob/1dc4adf947c16a36cb21ef63e1159264248127e8/R/estimate_infections.R#L362) 

vs writing a new one? Otherwise it should be the case of a new `stan_opts` function then updating the calling to use the `cmdsan` adapted fitting function.

**Comment by sbfnk** [comment]
updating https://github.com/epiforecasts/EpiNow2/pull/472/files#diff-18f5f36199932be5c40a48539480d34bdf00c5df886df369f94e499d148dfa2f

The branch is really not that different from `main`, which makes me think it should be fairly straightforward to support both.

**Comment by seabbs** [comment]
Yes - definitely agree. 

Just to note I am thinking about doing this the other way around with a companion package for `epinowcast` that has the models compiled using `rstan`. Not quite sure how that would work yet as unlike going from `cmdstanr` -> `rstan` I don't think you can convert `rstan` objects to work with `cmdstanr` functions (in the way you can the other way around).
