### ISSUE TITLE
Quick start in README vs. workflow vignette

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#482]
There is a fair amount of duplication between the [quick start section in the README](https://epiforecasts.io/EpiNow2/dev/index.html#quick-start) and the [workflow vignette](https://epiforecasts.io/EpiNow2/dev/articles/estimate_infections_workflow.html).

I wonder if there's a case for shortening the README to take out the code examples in the Quick start section and moving any of the bits that aren't in the vignette yet there (e.g. the paragraph on estimating delays), and instead pointing to the vignette.

**Comment by seabbs** [comment]
Do you know what current thinking is on having a readme quick start vs linking out to a vignette?

**Comment by sbfnk** [comment]
I guess this? https://r-pkgs.org/other-markdown.html#sec-readme

Which perhaps is what there is at the moment. Or perhaps the package doesn't solve any simple problems, which makes the whole thing more involved straight away.

I'm really not particularly inclined one way or the other, just that looking at the using examples vs. specifying delays question I noticed how much we repeat the same examples across the package (which might be a good thing, just gets cumbersome when wanting to make changes).

**Comment by sbfnk** [comment]
One example I personally like is the `rstanarm` [README](https://github.com/stan-dev/rstanarm).

Perhaps we could have something like:
- 1-2 paragraph high-level summary
- Arrows for:
  1. more detail
  2. models contained (estimate_infections, estimate_truncation, estimate_secondary, estimate_delay)
- Resources (links to vignettes including getting started)
- Installation
- Contributing

**Comment by jamesmbaazam** [comment]
> One example I personally like is the `rstanarm` [README](https://github.com/stan-dev/rstanarm).
> 
> Perhaps we could have something like:
> 
> * 1-2 paragraph high-level summary
> * Arrows for:
>   
>   1. more detail
>   2. models contained (estimate_infections, estimate_truncation, estimate_secondary, estimate_delay)
> * Resources (links to vignettes including getting started)
> * Installation
> * Contributing

You have my upvote. I've always thought the quick start section of the "README" could be moved to the "Getting Started" vignette because currently, the readme is quite long and intimidating.

**Comment by seabbs** [comment]
> "Getting Started" vignette because currently, the readme is quite long and intimidating.

In some sense this just moves the problem as then the getting started vignette will be intimidating! Would be good to work on this though potentially it is just a little bit of an intimidating tool.

**Comment by jamesmbaazam** [comment]
> In some sense this just moves the problem as then the getting started vignette will be intimidating!

I don't think so. I think it's more about how much information a NEW user is bombarded with when they land on the page. It's good to ease the user into the information you want to give them. 

On the landing page, they'll see what the package does and with what functions, then they'll wonder, "how can I use function x then?" -> Getting started vignette

"Okay, that was easy but that's not how it works in real life. I usually have to do a lot of things before getting to this step" -> (workflow vignette)

"How do I connect these ideas?" -> case studies

**Comment by seabbs** [comment]
Fair enough. Have you seen any literature discussing this? Seems to hang on whether people clicking through things reduces the burden on them - which I imagine it probably does to some degree unless they can't find the things to click (which happens to a lot of users).

**Comment by jamesmbaazam** [comment]
This [article](https://escholarship.org/uc/item/09q8p7gn) has good references on the topic.

For example, 

* Arguments for using hypertext format for presenting complex ideas
- [Hypertext Learning Environments, Cognitive Flexibility, and the Transfer of Complex Knowledge: An Empirical Investigation](https://journals.sagepub.com/doi/10.2190/4T1B-HBP0-3F7E-J4PN)

* Arguments for using linear (non-hypertext) presentation versus non-linear (hypertext) presentation of complex ideas
- [The Effects of Hypertext on Reader Knowledge Representation](https://journals.sagepub.com/doi/abs/10.1177/154193128803200512?journalCode=prob)

**Comment by seabbs** [comment]
Amazing! I'll git it a read.

**Comment by jamesmbaazam** [comment]
Enjoy. Very interesting literature.

**Comment by seabbs** [comment]
> Makes me wonder if we might want to set up a small user survey via

That is an interesting idea. `data.table` recently put out a survey though I am not sure about putting it in `.onLoad()` - feels a bit invasive?

**Comment by jamesmbaazam** [comment]
Oh, I just looked it up. I suggested `.onLoad()` because it's the closest to a user who doesn't interact with GitHub. I think the README would be a good place too. Not sure what the general practice is but could dig around if we think it's a good idea to carry it forward.  Linking to the thread for the data.table survey here for future reference https://github.com/Rdatatable/data.table/issues/5686.

**Comment by jamesmbaazam** [comment]
I really like the change to the epinowcast README (dropdown arrows so cool 🤩 ) and "Getting Started" vignette here https://github.com/epinowcast/epinowcast/pull/375. 

Should I go ahead with this PR?

**Comment by jamesmbaazam** [comment]
@seabbs and @sbfnk 

I'm working on this and have a few questions:

1. Should this PR just focus on moving things around then having follow-up PRs to remove the duplications between the the Getting Started vignette and `estimate_infections()` workflow vignette?
2. In the [contributing section](https://github.com/epiforecasts/EpiNow2#contributing) in the README, I would suggest we remove "Please note that due to operational constraints priority will be given to users informing government policy or offering methodological insights" and decide on this on a case-by-case basis when we get contributions as it might discourage new contributors. 
3. Is this a good time to remove the reporting templates section subject to the conversation in #495?

**Comment by sbfnk** [comment]
I see you've answered (1) with yes which makes sense to me.

(2) I agree

(3) I think so, yes - though can be done in a follow-up PR to keep things clear/contained.

**Comment by jamesmbaazam** [comment]
> though can be done in a follow-up PR to keep things clear/contained.

True.

**Comment by seabbs** [comment]
> "Please note that due to operational constraints priority will be given to users informing government policy or offering methodological insights"

This is yet more legacy from when we were getting multiple support emails a day so can definitely go.
