### ISSUE TITLE
Is `EpiNow2::update_list()` `utils::modifyList()`?

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#488]
I believe `update_list()` does the same job as [`utils::modifyList()`](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/modifyList). If I'm right, I guess it might be better to use the latter to remove duplication.

See demo [here](https://www.r-bloggers.com/2020/09/r-treasures-modifylist/).

**Comment by seabbs** [comment]
Nice! Certainly looks like it does the job. @nikosbosse for awareness as I think you had a version of this in `scoringutils`?
