### ISSUE TITLE
Fix default value for `generation_time` in `regional_epinow()`

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#494]
the default argument for `generation_time` should be `generation_time_opts()` as in `estimate_infections()`, but that is an issue outside this PR.

_Originally posted by @sbfnk in https://github.com/epiforecasts/EpiNow2/pull/476#discussion_r1376306615_

**Comment by sbfnk** [comment]
And in `epinow()`
