### ISSUE TITLE
Reporting templates and the `report` package

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#495]
EpiNow2 has [reporting templates](https://github.com/epiforecasts/EpiNow2#reporting-templates) and are briefly mentioned in the README but there's no guidance on how exactly to use them or whether we even encourage users to use them. I recently came across the [report package](https://easystats.github.io/report/) that provides nice methods for reporting fitted models from the common modelling functions in R like `lm`, etc, and other well known model objects from the Bayesian world like `brms` and `rstanarm`. 

I wonder if we could/should upgrade the templates here to methods to work with the S3 classes returned by the various functions, especially after the work in #451, or whether it would be better to [contribute `reports` methods](https://easystats.github.io/report/articles/new_models.html) to the {reports} package and link there.

Thoughts?

**Comment by seabbs** [comment]
Indeed. So we used these initially for our reporting and as far as I am aware no one else has ever used them.... (that being said its hard to know). I think one option would be just to remove these templates? 

The `report` package looks nice but I am not sure `EpiNow2` (despite being amazing) is quite the kind of thing they want to support? As an alternative we could have a support package that contains this new `report` method perhaps or something similar?

**Comment by jamesmbaazam** [comment]
> The report package looks nice but I am not sure EpiNow2 (despite being amazing) is quite the kind of thing they want to support?
I would also imagine how much of a burden it would be to always have to fix issues downstream in `reports` if the EpiNow2 API changes. 

> As an alternative we could have a support package that contains this new report method perhaps or something similar?

Yes, like {EpiNow2Extras} 🔥

**Comment by seabbs** [comment]
Yes exactly. @sbfnk was interested for a while in making a little package ecosystem and moving things like `regional_epinow` into their own support package (and perhaps generalising to work better across the model functions). That still seems like a good idea but perhaps relatively time/resource intensive.

In the first instance perhaps we should just drop these templates as we don't really want to support them or at least remove references to them in the README (or in the soon to be getting started guide).

**Comment by jamesmbaazam** [comment]
What was the agreement here? Are we removing the reporting templates and all references to them?
