### ISSUE TITLE
gamma_dist_def: scale is inverse scale?

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#498]
It looks like in `gamma_dist_def` that scale is actually its inverse? This matches with the stan parameterization (which was passed in some models as alpha beta) but not with the R version. 

https://github.com/epiforecasts/EpiNow2/blame/961c8c91063c6da381633ada387e2fba0337c101/R/dist.R#L340

THe renaming slipped through in the recent work on `dist_spec` but I am not clear if there was a deeper functionality issue and if that remains.

**Comment by sbfnk** [comment]
True but then it's passed (positionally) as inverse scale in
https://github.com/epiforecasts/EpiNow2/blob/af8c1f3fc3c844497a246c60b934ccad5420c362/R/dist.R#L102

Both should probably be fixed as part of #356
