### ISSUE TITLE
Safeguards against partial matching

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#499]
Do we want to keep using match.arg or switch to the rlang version which doesn't allow partial matching? This is probably something that requires a new issue but just noting here whilst I think of it.

_Originally posted by @seabbs in https://github.com/epiforecasts/EpiNow2/pull/476#discussion_r1377963069_

**Comment by seabbs** [comment]
I'm very open to switching. It seems like a good idea. There are other nice things in `rlang` as well so not a massive issue picking up a new dependency (if it is new?)

**Comment by jamesmbaazam** [comment]
Great. `rlang` is already being imported here.
