### ISSUE TITLE
Documentation of `reported_cases` should not refer to integers

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#506]
Currently this says: "confirm must be integer" but according to [the latest discussion](https://github.com/epiforecasts/EpiNow2/pull/476#issuecomment-1761337519) it does not have to be.

**Comment by jamesmbaazam** [comment]
Yes, true. The documentation for `check_reports_valid()` says it expects a `numeric`, based on linked discussion.
