### ISSUE TITLE
forecast_infections

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#509]
To bring `estimate_infections` into line with `forecast_secondary` and friends there should the the option of forecasting infections in `forecast_infections`.

This would work in the same way as `simualte_infections` but instead of taking a modified Rt time series it should simulate the generative process for the Rt model when not contained in the posterior predictions. This would decoupled forecasting from estimation. 

See `simulate_infections` here: https://epiforecasts.io/EpiNow2/reference/simulate_infections.html

**Comment by sbfnk** [comment]
I agree with this, but to be in line with the secondary models shouldn't it be the other way round? `simulate_infections` from parameters and `forecast_infections` from an existing estimate? Or we swap them for the secondary model.
