### ISSUE TITLE
Consistency in documentation style

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#510]
Would be nice to adopt a consistent style in the documentation in upcoming documentation and apply it retrospectively as well. 

I would suggest the following:

* Functions should be written as `[function()]` (especially with the closing brackets to differentiate from objects or function arguments).
* Objects and arguments as `object` or `argument`.
* Classes as `<class>`, for example, "An `<data.frame>`".

Thoughts?

**Comment by sbfnk** [comment]
Sounds good to me.
