### ISSUE TITLE
Deprecate `report_cases`, `sample_approx_dist` and `adjust_infection_report`

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#520]
As part of this we could probably deprecate `sample_approx_dist` and `adjust_infection_report`, and replace `dist_skel` with a simpler version that just calculates the pmf in line with #411

_Originally posted by @sbfnk in https://github.com/epiforecasts/EpiNow2/issues/504#issuecomment-1810697905_

**Comment by sbfnk** [comment]
All the relevant functionality there could be done using the `simulate_secondary` model.

**Comment by seabbs** [comment]
yup good idea
