### ISSUE TITLE
Change all priors to new dist interface, not just delays

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#525]
For a future PR this should probably be updated to use `normal()`.

_Originally posted by @seabbs in https://github.com/epiforecasts/EpiNow2/pull/504#discussion_r1408162989_
            
This will require moving the conversion to discretised distribution to the processing for stan (which is possibly a good idea anyway).

**Comment by sbfnk** [comment]
Will be picked up once #504 is merged.

**Comment by jamesmbaazam** [comment]
The linked comment does not lead anywhere so I'm struggling to get the context. I came [here](https://epiforecasts.io/EpiNow2/articles/estimate_infections_workflow.html#initial-reproduction-number) after seeing the code chunk here needs to be updated.
