### ISSUE TITLE
specify tolerance instead of max for distributions

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#533]
Instead of specifying the maximum one could support specifying a tolerance, i.e. minimum `pmf` / `1-cmf` as is already implemented in the convolution (or the conversion to stan code if going with the approach in #504). This might require looping over incremental values of `max` to find the "correct" one.

**Comment by seabbs** [comment]
Yes nice idea

**Comment by sbfnk** [comment]
As we can doing this in the conversion to stan code everywhere now, closing this as no longer a priority.
