### ISSUE TITLE
Move to `{cli}` for messaging

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#546]
One reason to do so:

https://github.com/epiforecasts/EpiNow2/pull/534#issuecomment-1943972293

**Comment by jamesmbaazam** [comment]
I just came across this rlib .lintr setup that checks if existing or incoming code uses base R condition handlers: https://github.com/r-lib/pkgdown/blob/819cede3fbbb2410912f4d49365177c9159b809f/.lintr.R.

We can add it after implementing this.

**Comment by jamesmbaazam** [comment]
Working on this now. PR incoming.
