### ISSUE TITLE
`<dist_spec>` is superclass of `list`

### ISSUE THREAD

**Issue by joshwlambert** [epiforecasts/EpiNow2#553]
Is it intentional that `<dist_spec>` is a superclass of `list`?

This issue follows on from a discussion with @sbfnk and @Bisaloo. Generally, it is unconventional for a custom S3 class to be a superclass of a base R class (in this case a list). The line where the class assignment takes place is https://github.com/epiforecasts/EpiNow2/blob/main/R/dist.R#L1060. 

This was first spotted when developing an S3 method for converting `<dist_spec>` objects. The dispatch is to `foo.list()` and then to `foo.dist_spec()` (using `NextMethod()`). 

If this implementation is due to reasons I've missed then I'm happy to close this issue, alternatively, I'm happy to submit a PR making `<dist_spec>` objects a subclass of `list` and can check if this breaks anything in other {EpiNow2} functions or documentation.

**Comment by joshwlambert** [comment]
Taking a closer look at #504 it seems this has already been addressed: https://github.com/epiforecasts/EpiNow2/pull/504/files#diff-f5d3dc82b7999539f0191ee11d29d5f2c358f0c41d116d75ffb4010ed6d09085R1803

**Comment by sbfnk** [comment]
Ah, thanks and sorry I couldn't remember the details of this. I'm pretty sure that was a reflection of my incompetence rather than following a specific rationale.
