### ISSUE TITLE
Setting seeds in tests

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#558]
At the moment we set seeds in two places in the tests
https://github.com/epiforecasts/EpiNow2/blob/23229a881b0904e53629101dc788efc48d3c94f8/tests/testthat/test-report_cases.R#L9
https://github.com/epiforecasts/EpiNow2/blob/23229a881b0904e53629101dc788efc48d3c94f8/tests/testthat/test-stan-convole.R#L18

In principle just setting this once (e.g. in `tests/testthat/setup.R`) should be enough. I'm not sure pseudo-random number generation is platform-independent and we see intermittent fitting failures so the seed might not be fully propagated but this seems at least seems worth trying/investigating.

**Comment by seabbs** [comment]
we also need to make sure the seed is being set within stan code

**Comment by seabbs** [comment]
oo interesting - it sounds like yes?

**Comment by sbfnk** [comment]
On reflection I'm no longer sure this is a good idea. It means that any time e.g. a test is added that generates a random number all the snapshots need to be updated. Perhaps instead a seed should be set in every test file, or perhaps even within every test that generates at least one random number?

**Comment by seabbs** [comment]
yes that seems very bad. 

> perhaps even within every test that generates at least one random number?

Sadly this one I think

**Comment by sbfnk** [comment]
On further reflection: the tests should really pass whatever the random seed unless they're snapshot tests. So I think we should only set a seed when snapshotting and then unset it again afterwards.
