### ISSUE TITLE
Author function tags

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#561]
We current have a few fair quite out of date author function tags (as the functions have been refactored a few times). I also don't personally like them as a way of sharing credit as they don't capture all the other parts of software dev well and as above often get out of date due to small changes (it isn't clear how these should be captured). 

I propose we remove them all and deal with credit via the the news and authorship list.

**Comment by sbfnk** [comment]
Yes, I agree. Emacs adds them automatically along the rest of the roxygen tags but I'll see how to deactivate that.
