### ISSUE TITLE
stan model implementation of `simulate_secondary`

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#563]
`simulate_secondary` is a nice function for convolutions with potentially time-varying delays and scaling, implemented in R.

Whilst this is great I think it would be nice to have a `simulate_secondary` function that mirrors `simulate_infections` and uses the corresponding stan model to simulate from given parameters. This could benefit from further model updates (and already e.g. can handle gamma distributed delays) and e.g. the new distribution interface but for the moment wouldn't be able to have time-varying convolution parameters. Implementing this would also enable the deprecations mentioned in #520.

We could
1. replace `simulate_secondary` with the function outlined above
2. keep `simulate_secondary` and add the function outlined above with different name
3. rename `simulate_secondary` and add the function outlined above as `simulate_secondary`
4. not do anything and keep things as they are

My initial inclination would be (3) with an aim to eventually deprecate the function when time-varying convolutions become available in the stan model.

**Comment by seabbs** [comment]
agree

**Comment by sbfnk** [comment]
Moving this to 1.5.0 so as to be able to bring forward #520 in the aim for a "cleaner" 2.0.0.
