### ISSUE TITLE
Group deprecated functions together in `pkgdown` Reference Page

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#583]
It would be nice to add a section in the `pkgdown` Reference, similar to [this section on superseded functions in dplyr](https://dplyr.tidyverse.org/reference/index.html#superseded) and [purrr](https://purrr.tidyverse.org/reference/index.html#superseded). That will probably help users identify which functions are deprecated all in one place.

**Comment by sbfnk** [comment]
I agree, and probably also to move them all to `R/deprecated.R`

**Comment by sbfnk** [comment]
The [lifecycle vignette](https://cran.r-project.org/web/packages/lifecycle/vignettes/communicate.html) recommends removing deprecated functions from `pkgdown` altogether (unlike superseded ones which aren't scheduled for removal) so will go with that when addressing #598.
