### ISSUE TITLE
Links in package README not going to website

### ISSUE THREAD

**Issue by athowes** [epiforecasts/EpiNow2#596]
Type of issue:
Commenting on existing documentation

Detail:
Some links in the package README don't send me to the package website. For example, the link to "Getting started vignette" is to https://github.com/epiforecasts/EpiNow2/blob/main/EpiNow2.html (which is a 404 for me). I was particularly looking at the links in the [resources section](https://github.com/epiforecasts/EpiNow2?tab=readme-ov-file#resources).

**Comment by jamesmbaazam** [comment]
> could this be linked to the move to relative links?

It is. I'll take a look.
