### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#625]
Would anyone - especially someone already funded to do `EpiNow2` development (i.e @sbfnk or @jamesmbaazam) be interested in taking over as a maintainer? 

I think I need to take a step back from this due to ongoing issues getting support to put time into this and more generally being disconnected from the current development goals which I think is making acting as a maintainer difficult.

I expect to still be implementing features and I am happy to contribute reviews and comment on design decisions. I am also open to having a discussion as to whether it would be best for me to stay as the designated maintainer/CODEOWNER.

**Comment by seabbs** [comment]
> Yes, can definitely do if you feel it's a drain

Great

**Comment by jamesmbaazam** [comment]
> Although I'm not entirely sure how this works.

In the CRAN sense?

**Comment by sbfnk** [comment]
> > Although I'm not entirely sure how this works.
> 
> In the CRAN sense?

Yes - or in any sense really.

**Comment by Bisaloo** [comment]
There is no formal way to declare co-maintainership. In particular, CRAN policy are quite explicit that there needs to be a single point of contact with them.

In practice, co-maintainership works pretty much the way you've work for the past months (or more) as far as I can tell:

- maintainers discuss issues and review PR together and give input for important changes to the package.
- releases are announced and coordinated by the official maintainer via `usethis::use_release_issue()`

If you want some examples of co-maintainership: https://github.com/r-lib/lintr (https://github.com/r-lib/lintr/pull/2529 & https://github.com/r-lib/lintr/issues/2392#issuecomment-2011292190); https://github.com/Rdatatable/data.table

If you want ways to announce this co-maintainership to potential contributors, I would recommend you do it in one of these places:

- `CODEOWNERS`
- `GOVERNANCE.md`
- `README.md`

**Comment by jamesmbaazam** [comment]
Thanks @Bisaloo.
