### ISSUE TITLE
Relative links in README

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#659]
These trigger NOTEs which we'll need to minimise for CRAN submission.
https://github.com/epiforecasts/EpiNow2/issues/652#issuecomment-2100096631

**Comment by jamesmbaazam** [comment]
Two options here:

- Aspirational links, e.g., for `regional_epinow()`, https://epiforecasts.io/EpiNow2/reference/regional_epinow.html.
- Not hyperlinked.

**Comment by sbfnk** [comment]
> * Not hyperlinked.

This seems like the more sensible option to me, so as not to confuse people between dev/stable version docs.
