### ISSUE TITLE
CITATION file uses unset `meta$Date`

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#668]
Flagged in post-publication CRAN review as causing a WARNING there

**Comment by sbfnk** [comment]
The fix didn't fix it (because the date is not NULL but POSIX or something similar).

CRAN maintainers have been really helpful in trying to sort this out:

> There are really two issues here.

> One, the current CITATION code is very complicated and uses non-exported
functions from utils, which should be avoided.  Afaict, the intention is
to use the auto-generated citation with the zenodo DOI added.  In this
case, one could simply do

> bibentry("Manual",
         doi = "10.5281/zenodo.3957489",
         other = unlist(citation(auto = meta), recursive = FALSE))

> However,

> (a) CRAN will eventually also get DOIs for the packages

> (b) Afaict, the given DOI pertains to a specific version of the package,
which is *not* the current CRAN version.  So I think it would be better
to use

>   citation(auto = meta)

> and provide a bibentry with the *static* bib info corresponding to the
particular doi given.  Which is version 1.4.0 and has Published
September 26, 2023, hence year should be 2023 and there is no need to
dynamically compute it in the CITATION file.

We could
1. stop doing Zenodo releases, or
2. continue to do them and then make sure to update before every release

(1) might be a good option in the light of (a) above?

**Comment by sbfnk** [comment]
@seabbs any thoughts on how important the Zenodo releases are, and whether we want to continue them?

**Comment by sbfnk** [comment]
Also should the Zenodo release be updated automatically?

**Comment by seabbs** [comment]
I'm not sure why we wouldn't just use the overarching zenodo release doi (which doesn't need to be updated).

That being said I have no strong opinion about including the zenodo doi in the citation. I do think we should keep doing them in general though as its no cost and potential is a useful archive for people

**Comment by sbfnk** [comment]
The DOI perhaps doesn't need to be updated but then new releases still need to be added - how does the Zenodo release get updated when there is a new github release? Should this be happening automatically?

**Comment by sbfnk** [comment]
Is the fact that it's not happening a zenodo issue then?
https://github.com/zenodo/zenodo/issues/2243

**Comment by seabbs** [comment]
yes - unless it has somehow become unlinked

**Comment by seabbs** [comment]
Just checked - it had. I think it won't pick up the new release but it should pick up any releases from now

**Comment by sbfnk** [comment]
Thanks!
