### ISSUE TITLE
Should `rt_opts()` accept `NULL`?

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#686]
It would be more streamlined if `rt_opts()` accepted `NULL` (since it is an option) as it would be more aligned with the current workflow of passing options to the `_opts()`. Currently, `rt_opts()` errors with `NULL`, which suggests an inconsistency in how arguments are expected to be specified.

**Comment by sbfnk** [comment]
Which argument of `rt_opts()` do you mean?

**Comment by jamesmbaazam** [comment]
I was thinking the `prior` argument could accept `NULL` and take precedence, if specified. However, I am also aware that setting an argument to `NULL` as a way to turn off the argument is also idiomatic in R. 

I caught myself trying to set `rt` to NULL by passing it to `rt_opts()` and wondered if users would also think the same way😬.

**Comment by jamesmbaazam** [comment]
Closing this issue because the current implementation is idiomatic in R. Setting an argument to NULL as a way to turn off the argument is a common practice.
