### ISSUE TITLE
`epinow()`'s "timing" output should include units

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#687]
Is your feature request related to a problem? Please describe:

I'm using the `epinow()` function to run and compare the run times of various model specifications to address #629. I am particularly interested in the "timing" output of `epinow()` but it currently prints a number without units, so it is not interpretable.

Describe the solution you'd like:

The "timing" output of `epinow()` should include units. The following line https://github.com/epiforecasts/EpiNow2/blob/49159067e2c430b81ca77108128d0d94a7a2f9a8/R/epinow.R#L289

can be changed to `sub("Time difference of ", "", capture.output(difftime(end_time, start_time)))` to fix the issue.

Additional context:
Add any other context or screenshots about the feature request here.ocument Title

**Comment by sbfnk** [comment]
Good point - however, would it not make more sense to just store the results of `difftime` (of class `<difftime>`? This would then leave the user with the option of printing (getting the nicely formatted output) or processing numerically.

**Comment by jamesmbaazam** [comment]
> This would then leave the user with the option of printing (getting the nicely formatted output) or processing numerically.

That's a good point. I've made the changes in the linked PR.
