### ISSUE TITLE
Failed installation, suspect may be due to bug in code?

### ISSUE THREAD

**Issue by nlinton** [epiforecasts/EpiNow2#689]
When trying to install EpiNow2 1.5.2, we get the error:

```Error in Rcpp::compileAttributes(pkgdir) : 
Evaluation error: /tmp/RtmpeUQAWK/R.INSTALL6de7e55a03229/EpiNow2/R/extract.R:100:34: unexpected input
99:   samples <- split(samples_df, by = "variable")
100:   samples <- purrr::map(samples, \
```

For 1.5.0 we saw a similar error (but it had not been present when previously installing 1.5.0 successfully when 1.5.0 was first launched). 

```
Error in parse(text = lines, srcfile = srcfile(file), keep.source = keep.source) : 
 /tmp/Rtmpfy7X1d/R.INSTALL6e0f64bf359da/EpiNow2/R/extract.R:100:34: unexpected input
99:   samples <- split(samples_df, by = "variable")
100:   samples <- purrr::map(samples, \
```

The error location appears to be in `R/extract.R`

`100: samples <- purrr::map(samples, \(df) {`

where a function seems like it should be called but is not named.

**Comment by sbfnk** [comment]
what is the output of `R.version`? The syntax that throws an error was introduced in R 4.1.0 so if yours is older than this might cause the error.

The package is supposed to work with R versions >=3.5.0 though so it's something we should fix.

**Comment by nlinton** [comment]
We use >4.2. I'm told updating `Rccp` fixed the error so I'll close the issue because the problem was on our side!
