### ISSUE TITLE
set seed in vignettes

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#705]
At the moment changes that don't relate to changes in the model change the vignettes (see https://github.com/epiforecasts/EpiNow2/pull/700). This could be avoided by setting a seed early in the vignettes.

**Comment by jamesmbaazam** [comment]
Good point.

**Comment by jamesmbaazam** [comment]
Although I see all vignettes set the seed early. It might be the case that the set seed ought to be preserved throughout the session.

**Comment by sbfnk** [comment]
Hmm, ok this might require keeping an eye on then. If all the vignettes set seeds I can close this for now as the original issue does not exist.
