### ISSUE TITLE
Suggest installing `cmdstanr`

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#706]
The package now provides some `cmdstanr` functionalities that can only be accessed if `cmdstanr` is installed. We should suggest installing it in the README.

**Comment by sbfnk** [comment]
I think suggesting it might go to far (as people might not be able e.g. to compile code) but I do agree it's a good idea to say that it's an option that gives access to that functionality.

**Comment by jamesmbaazam** [comment]
I think we are likely saying the same thing.
