### ISSUE TITLE
Add actions to precompile long running vignettes

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#732]
@seabbs has implemented a nice workaround in https://github.com/epinowcast/epinowcast/pull/494 to re-compile long-running vignettes. We could implement it here as well.

**Comment by sbfnk** [comment]
I agree, this would be good to do.

**Comment by seabbs** [comment]
I'm tempted to make this a composite action like `epinowcast/actions/install-cmdstan` as its a lot of boilerplate to copy and paste all over the place?

**Comment by jamesmbaazam** [comment]
Yes, ideally, it would be one workflow that's triggered when any of the files are touched or changed. I couldn't find the `install-cmdstan` action though, only `check-cmdstan`. If there is no workaround, I don't think it's unmanageable to have one for each vignette given there is a manageable number.

**Comment by seabbs** [comment]
https://github.com/epinowcast/actions/tree/main/install-cmdstan

**Comment by jamesmbaazam** [comment]
Ah, I see now. That would really reduce the duplications.
