### ISSUE TITLE
Document/surface what settings are applied when `rt = NULL`.

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#761]
I've been thinking we should actually surface what settings are applied when `rt = NULL`. We only say that they can set it to NULL but we could add what settings are used when that is done. What do you think?

_Originally posted by @jamesmbaazam in https://github.com/epiforecasts/EpiNow2/pull/747#discussion_r1734718474_

**Comment by seabbs** [comment]
I think we might also want to move all the random walk + differencing etc settings. elsewhere (to i.e a latent argument). Then all models can use those features and we don't use anything by stealth. This would also mean getting rid of the gp arg (and passing it to the latent_opts as the model)

**Comment by jamesmbaazam** [comment]
> I think we might also want to move all the random walk + differencing etc settings. elsewhere (to i.e a latent argument). Then all models can use those features and we don't use anything by stealth. This would also mean getting rid of the gp arg (and passing it to the latent_opts as the model)

I'm all for exposing all settings that have been set under the hood. Looks like it deserves its own issue thread.
