### ISSUE TITLE
Weekly random walk estimator no longer working as expected

### ISSUE THREAD

**Issue by martinamcm** [epiforecasts/EpiNow2#767]
Summary:
When using the random walk estimator on weekly aggregated reported cases, case counts are overestimated as it is no longer effectively mapping between the daily infections and weekly reported cases.

Description:
We have embedded the EpiNow2 package in a nowcasting pipeline that we have been using for the past year. Our data is reported weekly so the estimators we use in the `epinow()` call to allow for this are `rt = rt_opts(prior = list(mean = 2, sd = 0.2), rw = 7)` and `obs = obs_opts(week_effect = TRUE)`. The output estimates for `reported_cases` have always been zero for the 6 days of the week where no data is observed and non-zero on the day of the observation. We have been extracting the non-zero weekly estimates and have created figures from this on a weekly scale. 

As of last week, some element of the estimation may have changed because when applying to the weekly data, it seems to assume the reported cases are on a daily scale hence substantially overestimating the case counts. It still seems to recognise the week effect (as per the figure) but the difference is that estimates for all other 6 days in the week for which there is no reporting are now also non-zero and it doesn't seem to recognise the weekly reporting structure anymore. Are there changes to the underlying estimation methods in recent weeks? We only noticed this change as of last week. Happy to provide more details if needed. 

![weekly_epinow](https://github.com/user-attachments/assets/b39873bb-2452-4122-9ffb-f5c897c30f2d)

Reproducible Steps:
As stated above the data in epinow() call is the weekly data and with the modifications to the input arguments detailed above. 

EpiNow2 Version:
The version of EpiNow2 you are running: 1.5.2

---------

**Comment by sbfnk** [comment]
Am I right in thinking that this was happened following a package update to version 1.5.2? If so then this might be related to an update in the handling of missing data that perhaps wasn't communicated well enough. In that case you have two options:

### Option 1 (should restore previous behaviour): fill with zeroes
Assuming your data is in a data frame called `cases_weekly`:
```{r}
library("data.table")

cases_daily <- data.table(
  date = seq(min(cases_weekly$date), max(cases_weekly$date), by = "day")
)
cases_daily <- merge(cases_daily, cases_weekly, by = "date", all.x = TRUE)
cases_daily[, confirm := nafill(confirm, type = "const", fill = 0)]
```
and then use `cases_daily` in the call to `epinow`.

### Option 2 (a more sensible model): accumulate estimates to observations

Add `obs_opts(na = "accumulate")` to the call to `epinow`.

**Comment by sbfnk** [comment]
Tagging @jamesmbaazam and @seabbs who have helped drill down on the underlying issue.

**Comment by seabbs** [comment]
To expand on @sbfnk answer option two is more "sensible" because rather than trying to estimate the weekly reporting pattern we use it directly (as we know it is weekly reporting). This should speed up fitting and make things more stable across the board.

**Comment by martinamcm** [comment]
Thanks all for the fast response and straightforward solution!! And congrats on an excellent package - we use it a lot in WHO HQ and in some of the regional offices in our outbreak response work! 

⁠

**Comment by jamesmbaazam** [comment]
Thanks @martinamcm. Also feel free to make suggestions to improve the documentation of the features you regularly use.

**Comment by jamesmbaazam** [comment]
@martinamcm Could you indicate if the suggestions provided here solved your issue? If it did, we could close this issue.

**Comment by seabbs** [comment]
@jamesmbaazam I think this indicates we need to add some kind of mitigation for other users before closing.

**Comment by jamesmbaazam** [comment]
A backward compatible approach could be to have the default be NA treated as 0. So, something like obs_opts(na = c("zero", "missing", "accumulate").

**Comment by martinamcm** [comment]
Thanks a lot all - I've tested it out and it's working well now! I've included the updated figure below on the same data for reference, in case helpful! 

@jamesmbaazam regarding extra documentation, I think that at some point it could be useful to add a short, dedicated section on applying to weekly data. The current documentation mentions the rw estimator for weekly, but I think having a section with an example as you do for daily could be beneficial to others as we work a lot with weekly aggregated data. The other thing would probably be then to be able to visualize on weekly scale too, but as it's possible for end users to extract the estimates and create visuals I don't think it's really necessary. 

<img width="505" alt="weekly_est_epinow" src="https://github.com/user-attachments/assets/77fe349e-caf2-4106-b4a3-1c3e677cb2b3">

Thanks again for your help and for a great package!

**Comment by jamesmbaazam** [comment]
Thanks for the update and the feedback on documentation, @martinamcm. The accumulation feature pointed out here for use with temporally aggregated data was only recently added and could definitely benefit from being documented better especially with an example. I will raise an issue to that effect.

**Comment by sbfnk** [comment]
Thanks all. Closing this as the issue at hand has been solved - any changes to the package following from the points noted here can be discussed in separate issues.
