### ISSUE TITLE
Add message explaining new behaviour when `obs_opts(na = "missing")`

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#771]
Based on #767, @seabbs has suggested we add a message in `obs_opts()` to explain the new behaviour when `na = missing`. This will help users decide whether to use the new behaviour or retain the old one by preprocessing their data as suggested in https://github.com/epiforecasts/EpiNow2/issues/767#issuecomment-2348805272.

**Comment by sbfnk** [comment]
I agree, we should print a message when `na` is not set by the user and there are missing dates in the data.

Related comment and original change in https://github.com/epiforecasts/EpiNow2/pull/528#issue-2047633138
