### ISSUE TITLE
Add colours to `dist_spec` plot

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#786]
> I would suggest using color instead of line types to differentiate between pmf and cmf. Since there are only two levels, the color aesthetic plays nicely with the current default of "cumulative = TRUE" for uncertain distributions.

_Originally posted by @jamesmbaazam in https://github.com/epiforecasts/EpiNow2/issues/784#issuecomment-2363409363_

**Comment by jamesmbaazam** [comment]
Is there a preferred color scheme here?
