### ISSUE TITLE
Improve documentation for those passing in a GI

### ISSUE THREAD

**Issue by kaitejohnson** [epiforecasts/EpiNow2#793]
Type of issue:
Commenting on existing documentation/ language in vignettes

Detail:
While the model definition makes it clear that the implementation of the renewal approach expects time indexing starting at day 1, those not reading the model definition carefully may miss this. I think it would be nice to flag to the user that if they pass in a vector to the GI, its assumed to be 1 indexed not 0 indexed (so the first value reflects the probability of transmission on day 1 of infection not day 0, the day they were infected). 

Could add to:
- the main EpiNow2 vignette (would need to add an example where GI is being set by the user)
- the documentation for `generation_time` or `generation_time_opts`

---------

**Comment by seabbs** [comment]
Thanks @kaitejohnson this is a good point. We might also want to add some discussion of the user choice to either left truncate or to shift the distribution when passed as a vector
