### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#796]
With the recent switch to `{cli}` we now have 21 dependencies which is above CRAN's limit of 20 (not sure how strictly this is enforced). It would be good to consider which dependencies could be removed.

Candidates are:
- `{future}`, `{future.apply}`, `{futile logger}` and remove corresponding functionality, potentially not ideal as might be breaking for people using this in production
- `{R.utils}` - likewise only used for production for timing out long runs
- `{patchwork}` only used for two plots - could they be faceted instead?
- `runner::mean_run()` only used once, in `create_shifted_cases()`, also `truncnorm::rtruncnorm` only used in two places -- both of these could be re-implemented fairly trivially, but I'm not sure what the point of that would be.

Let's see how we do with the 1.6.0 submission and then potentially reconsider.

**Comment by sbfnk** [comment]
`progressr` perhaps could be optional

**Comment by seabbs** [comment]
I think making the parallel functionality optional is a good idea that is the sensible solution. I don't have the sense that many people use it.
