### ISSUE TITLE
Error if first element of a `NonParametric` generation interval PMF is non-zero

### ISSUE THREAD

**Issue by sbfnk** [epiforecasts/EpiNow2#806]
If `NonParametric` generation interval PMFs are going to be zero-indexed, I suggest erroring whenever there is non-zero mass in the 0 bin. I think this will cause the fewest (and the least costly) surprises for users.

_Originally posted by @dylanhmorris in https://github.com/epiforecasts/EpiNow2/issues/799#issuecomment-2383838793_

**Comment by seabbs** [comment]
I think we should be warning or informing in this case vs erroring as I think some users may want this. This is prior to any kind of change to not have the transform happen so under the scenes

**Comment by sbfnk** [comment]
But if users might want this they could just set the first element to zero?

If what you mean is to go through a deprecation cycle for this I agree.

**Comment by seabbs** [comment]
I changed my mind but yes agree on a depciation cycle
