### ISSUE TITLE
Is the current citation trackable by Google scholar etc

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#866]
It doesn't contain a DOI which makes me think it won't be. Historically we have used the zenodo DOI for this reason

**Comment by sbfnk** [comment]
I think you're right - we could use the CRAN DOI? https://doi.org/10.32614/CRAN.package.EpiNow2

**Comment by seabbs** [comment]
yes good idea or the zenodo one. We used to point people at the website paper but its not ideal really so I don't think we should go back to doing that.

**Comment by sbfnk** [comment]
This will come automatically in the next R version (it's already in [devel](https://github.com/r-devel/r-svn/blob/6ca9ee7a4dfc9aea256d30cd1042479bc5507170/doc/NEWS.Rd#L35) so I think we can just wait for it to happen automagically.
