### ISSUE TITLE
Allow changing the upper limit for projections?

### ISSUE THREAD

**Issue by nicholasdavies** [epiforecasts/EpiNow2#877]
`epinow` won't return quantiles greater than 10x the highest observed confirmed case number, which is very much defensible in practice. But I'm trying to generate some figures to illustrate how much data is needed to forecast effectively, and this ceiling is getting in the way of making comprehensible figures (see below).

<img width="416" alt="image" src="https://github.com/user-attachments/assets/c2f0f099-5ede-4d98-b492-327213625968">

Is there any way of overriding this ceiling? I'm sorry if I have missed it, but have looked through the documentation and searched through the code on github (searching for `10`) and couldn't find anything. I have probably missed something obvious.

**Comment by sbfnk** [comment]
Is this using the plotting functionality of EpiNow2? There's the `max_plot` argument in [`plot_estimates()`](https://epiforecasts.io/EpiNow2/reference/plot_estimates.html) which can be tuned. If I remember correctly the actual numbers returned by `epinow()` don't have this constraint.

**Comment by nicholasdavies** [comment]
Thanks so much Seb — inexplicably, I was trying to extract the quantiles from the `plot` member of the structure returned by `epinow`, rather than from `estimates$summarised`, or `estimated_reported_cases$summarised`. Was just looking in the wrong place and indeed the package already provides the functionality I was looking for.
