### ISSUE TITLE
Add the lifecycle package to all documentation + dev instructions for depreciating functions.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#88]
See the package docs for the intended use: https://lifecycle.r-lib.org/articles/lifecycle.html

This would be a useful feature as it would allow us to signal how stable functions are and easily communicate with users when changes are being made/planned.

**Comment by joeHickson** [comment]
Nice - I like the soft / hard deprecation :)

**Comment by seabbs** [comment]
Unfortunately not on CRAN so closing for now
