### ISSUE TITLE
Split up `create_stan_data()`?

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#887]
I've been reviewing #871 to bring myself up to date with developments while I was away and I realise that `create_stan_data()` is getting quite long and difficult to parse. For one, it's combining two concerns: what I'd call static data creation and dynamic modelling of the initial growth. I would suggest pulling out the modeling of initial growth part (https://github.com/epiforecasts/EpiNow2/blob/main/R/create.R#L504-L524) as it will be easier to maintain and improve if need be and to point to. It only depends on `data`, `seeding_time`, and `horizon` and returns the `prior_infections` and `prior_growth`, making it quite focused. This is more of a maintenance issue than an enhancement and can be categorised as low priority.

Thoughts?

**Comment by sbfnk** [comment]
Sounds good to me
