### ISSUE TITLE
Uninformative error for `plot.dist_spec()` when no max specified

### ISSUE THREAD

**Issue by jamesmbaazam** [epiforecasts/EpiNow2#895]
When a `<dist.spec>` does not have max specified, we don't get an informative error because the `if` check is inadequate. We need to also check that `is.null(attr(y, "max"))` in https://github.com/epiforecasts/EpiNow2/blob/88584d641522b73bbb7bd66da83a784e0936c056/R/dist_spec.R#L721

``` r
# This works
plot(EpiNow2::Gamma(0,1, max = 10))
```

![](https://i.imgur.com/9DoFn3E.png)

``` r
# This doesn't work as expected but the error message is not very informative
try(
  plot(EpiNow2::Gamma(0,1))
)
#> Error in if (is.infinite(attr(y, "max"))) { : argument is of length zero
```

<sup>Created on 2024-12-12 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by sbfnk** [comment]
> We need to also check that `is.null(attr(y, "max"))`

Good catch! The way to cover this would be to replace the check with a check for `if.infinite(max(y))`
