### ISSUE TITLE
Add progress bar support

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#93]
Supporting a parallel enabled progress bar would help users understand how far through their estimates are. The `progressr` package is a sensible option (https://cran.r-project.org/web/packages/progressr/vignettes/progressr-intro.html)

This issue is for planning, discussion and outlining the implementation. May be of interest to @joeHickson.

**Comment by joeHickson** [comment]
Marvellous - support for futures out the box :)
