### ISSUE TITLE
Expand hierarchical logging system and improve defaults

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiNow2#97]
Build on the changes introduced in #92 to more thoroughly nest logging, improve the robustness, and add improved defaults for users.

**Comment by hsbadr** [comment]
I think the current logging system is cluttered and don't include all the (debugging) information needed. I'd suggest to have a single log files in a chronological order with a PREFIX for each component (or at least allow for appending/merging into one file) and all Stan messages, if requested. For example, the log file may include:
```
Logging threshold set at INFO for the EpiNow2 logger
Logging threshold set at INFO for the EpiNow2.epinow logger
Logging threshold set at INFO for the EpiNow2.epinow.estimate_infections logger

Writing  logs to: ~/EpiNow2/log/2020-10-19.log

EpiNow2.epinow.estimate_infections: DEBUG [2020-10-19 13:13:26] Running in exact mode for 4000 samples (across 4 chains each with a warm up of 1000 iterations each) and 60 time steps of which 7 are a forecast

Chain 4:
Chain 4: Gradient evaluation took 0.017444 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 174.44 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4:
Chain 4:
Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 3: Iteration:  100 / 2000 [  5%]  (Warmup)
Chain 2: Iteration:  100 / 2000 [  5%]  (Warmup)
Chain 1: Iteration:  100 / 2000 [  5%]  (Warmup)
Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 2: Iteration:  300 / 2000 [ 15%]  (Warmup)
Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 3: Iteration:  300 / 2000 [ 15%]  (Warmup)
Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 2: Iteration:  500 / 2000 [ 25%]  (Warmup)
Chain 1: Iteration:  300 / 2000 [ 15%]  (Warmup)
Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 3: Iteration:  500 / 2000 [ 25%]  (Warmup)
Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 2: Iteration:  700 / 2000 [ 35%]  (Warmup)
Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 3: Iteration:  700 / 2000 [ 35%]  (Warmup)
Chain 1: Iteration:  500 / 2000 [ 25%]  (Warmup)
Chain 2: Iteration:  900 / 2000 [ 45%]  (Warmup)
Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 3: Iteration:  900 / 2000 [ 45%]  (Warmup)
Chain 1: Iteration:  700 / 2000 [ 35%]  (Warmup)
Chain 2: Iteration: 1100 / 2000 [ 55%]  (Sampling)
Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 1: Iteration:  900 / 2000 [ 45%]  (Warmup)
Chain 3: Iteration: 1100 / 2000 [ 55%]  (Sampling)
Chain 2: Iteration: 1300 / 2000 [ 65%]  (Sampling)
Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 3: Iteration: 1300 / 2000 [ 65%]  (Sampling)
Chain 2: Iteration: 1500 / 2000 [ 75%]  (Sampling)
Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 1: Iteration: 1100 / 2000 [ 55%]  (Sampling)
Chain 3: Iteration: 1500 / 2000 [ 75%]  (Sampling)
Chain 2: Iteration: 1700 / 2000 [ 85%]  (Sampling)
Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 2: Iteration: 1900 / 2000 [ 95%]  (Sampling)
Chain 3: Iteration: 1700 / 2000 [ 85%]  (Sampling)
Chain 1: Iteration: 1300 / 2000 [ 65%]  (Sampling)
Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 2:
Chain 2:  Elapsed Time: 125.93 seconds (Warm-up)
Chain 2:                103.382 seconds (Sampling)
Chain 2:                229.312 seconds (Total)
...
```

**Comment by seabbs** [comment]
Agree the logging needs some work in particular controlling the output by default.

 However two notes 1. the current default is really configured with the idea that you are running lots of places at once and therefore only shows summary info by default with everything else sent to secondary logs. 2. You can set up your own logging setup (i.e everything to a single log) easily either by using `setup_logging` or directly with `futile.logger` and turning off the package default by settings `logs = NULL` in `epinow`, `regional_epinow` etc. The docs should give some clues on that but again very happy to hear better ways of communicating or thoughts on whether these defaults make sense. 3. For `epinow` logging could potentially do with a different default as the running across many places issue is likely less of a problem. 

Adding the verbose stan output as an option would be really great but so far no luck getting that working with `futile.logger` which our collegues at the Met office are very keen we use as it gives them flexibility in setting up their own logs.

**Comment by hsbadr** [comment]
That makes sense. Thanks for the info!

Yes, it seems that running `regional_epinow`  with `futile.logger`  with `future = TRUE` suppresses `Stan` messages until after the `future_lapply` is executed, which is annoying. I think it's more of a parallel processing issue, since it seems to work fine with `epinow` and `future = FALSE`.

**Comment by seabbs** [comment]
Potentially users can resolve that particular issue using the settings in the future package (using some of the options in plan). I don't think this can be done within the package though.

**Comment by seabbs** [comment]
@hsbadr do you have any idea how to catch the output from stan (both the chain updates and any errors that occur). I have been able to do it with `capture.output` when running using a single core but when running in parallel have not been able to manage it. Had no luck looking for a solution elsewhere.

**Comment by hsbadr** [comment]
@seabbs I use `diagnostic_file`, along with `sample_file` and `append_samples = TRUE`, for debugging.

| Argument | Type |Description |
|:-----------:|:------:|:-------------|
| **diagnostic_file** | *character* | An optional character string providing the name of a file. If specified the diagnostics data for all parameters will be written to the file. If not provided, files are not created. When the folder specified is not writable, `tempdir()` is used. When there are multiple chains, an underscore and chain number are appended to the file name prior to the `.csv` extension. |
| **sample_file** | *character* | An optional character string providing the name of a file. If specified the draws for all parameters and other saved quantities will be written to the file. If not provided, files are not created. When the folder specified is not writable, `tempdir()` is used. When there are multiple chains, an underscore and chain number are appended to the file name prior to the `.csv` extension. |
| **append_samples** | *logical* | Only relevant if `sample_file` is specified and is an existing file. In that case, setting `append_samples=TRUE` will append the samples to the existing file rather than overwriting the contents of the file.

You can pass them to `EpiNow2` via `stan_args` (set the paths and filenames as you wish):
```
stan_args = list(
    ...
    diagnostic_file = file.path(
      getwd(),
      "diagnostics.csv"
    ),
    sample_file = file.path(
      getwd(),
      "samples.csv"
    ),
    append_samples = TRUE,
    ...
)
```

**Comment by seabbs** [comment]
Thanks @hsbadr, 

I gave this a whirl previously and it didn't return anything useful (diagnostics just contained the stan settings for example). Will give it a another shot.

**Comment by hsbadr** [comment]
I see. This happens when using `future` parallel processing with `rstan` in `EpiNow2`. BTW, `CmdStan` provides better diagnostics with `save_latent_dynamics`.

**Comment by medewitt** [comment]
I need to get back on the CmdStan version. Hopefully end of this week (been presenting local projections given explosion of cases...)

**Comment by seabbs** [comment]
Yup I can see that it would work with `future = TRUE`. I have seen some stability issues with that setting but will investigate as it seems like a better approach in general than relying on stan to do the parallisation. 

@medewitt no worries at all. It does seems like `CmdStan` offers some really nice benefits.

**Comment by hsbadr** [comment]
@seabbs Sounds good!

@medewitt Thanks for the heads up! Please let me know if I can do anything to help.
